### ISSUE TITLE
Play-by-Email (PBEM) missing

### ISSUE THREAD

**Issue by Ramblurr** [raceintospace/raceintospace#131]
Stumbled across this project today, and excitedly cloned it. Building was easy on my Fedora box.

I was looking forward to playing this game asynchronously with friends using the PBEM game mode, but I can't seem to find it.

Any idea where it is?

**Comment by rodneyrod** [comment]
What sort of changes would be required to implement a new solution then?

Getting multiplayer working again would be a killer feature.

**Comment by rodneyrod** [comment]
@mkmccarty What would be needed to get multiplayer working again?

**Comment by mkmccarty** [comment]
The multiplayer code hasn't been ported, but it's something someone could
work to implement.  I believe there are comments where the original code
was, plus the original code is in the repository.

The way that multiplayer worked was either PBM where files are exchanged or
via dialup.

If I recall correctly, Player 1 would take their turn, and the mission
results would be generated but not shown, the save file was encrypted and
sent to the other player.  Player 2 would take their turn, mission results
generated, prestige awarded, Player 2 could could watch the results then
complete season's saved file would be sent back to Player 1 to complete the
turn.  Player 1 would see their mission and prestige results and start
their next turn.  It was a fairly basic tweak to the normal gameplay.

**Comment by peyre** [comment]
It would be great to get PBEM working again.  It's the one thing that the CD version of BARIS has that RIS doesn't.  FWIW, the Modem option never worked in Windows, either natively in Win98 or when running in DOSBox (though it probably ran fine in Win3.1).

**Comment by peyre** [comment]
Incidentally, a bit more detail is available at PBEM.txt on the SourceForge site: [https://sourceforge.net/projects/raceintospace/files/PBEM.txt/download](url)

**Comment by TiPunch69** [comment]
Would be cool to bring this one back. In my opinion Play per Mail would be sufficient.

**Comment by peyre** [comment]
I've wanted it to happen for a long time now, for the reason I mentioned above.  Michael tells me it wouldn't be awfully difficult to put back in; we'd just have to write the code ourselves, which is unfortunately beyond my ability.

**Comment by rnyoakum** [comment]
I have no memory of how Play-by-Email should be working, because I never played RIS against a human opponent when Play-by-Email existed, so please bear that in mind.

I've been considering this issue, and my big concern deals with how mission execution is supposed to be handled. From @mkmccarty 

```
If I recall correctly, Player 1 would take their turn, and the mission
results would be generated but not shown, the save file was encrypted and
sent to the other player. Player 2 would take their turn, mission results
generated, prestige awarded, Player 2 could could watch the results then
complete season's saved file would be sent back to Player 1 to complete the
turn. Player 1 would see their mission and prestige results and start
their next turn. It was a fairly basic tweak to the normal gameplay.
```

I interpret this as the first (USA) player not seeing any of the mission steps during their initial turn, only learning of success or failure in a replay done at the beginning of the next season. This is easier to execute from the perspective of creating the save - the USA player creates a normal two-player game, runs through the first turn, and saves the game as a Play-By-Email file. But it has ramifications on the mission execution, namely:

1. I recall encountering a mission fail state where the game asked me if I wanted to continue or abort the mission, and
2. Players are normally given the opportunity to scrub each mission before executing it.

Assuming I'm not imagining (1), that would make pre-generating mission results inviable, because there could be an error state that demands player input. For (2), there are multiple scenarios where a player would reasonably scrub a mission depending on the outcome of the previous mission(s) - both theirs and their opponents. Now, both of those problems can be solved by taking away player agency, but that's a solution I'd rather avoid.

Another way to handle PBEM is for each player to execute their turn and resolve their missions, ignorant of the other player's actions. They would (possibly) see a summary page after each mission telling them which prestige events they accomplished, minus the prestige analysis. Then, having completed all their missions, the 2nd player would see any prestige firsts their opponent achieved, would send the file back, and the 1st player would then see any prestige firsts their opponent achieved as well as the full summary page for their missions complete with prestige analysis.

While I think the second approach solves the game-play concerns, staging missions at the end of each player's turn requires the game to know which type of game it is **when it's created**, and not when it's saved. Otherwise, it won't know to change when mission execution occurs. As far as I know there is no selector for choosing game type in the New Game screen, so that would mean creating a new selection system.

*A* solution would be to have the game play normally, and when each player decides to end their turn - instead of clicking on the flagpole - they enter the Time Capsule and save the file as a PBEM save. The player then plays out their missions, the results of which are recorded in the new save file. In this way, it operates much as the second approach, but uses the Time Capsule to conclude a turn rather than the Flag Pole. This solution would resolve most of the technical issues, but seems inelegant, and isn't intuitive.

Am I missing something? Thoughts?

**Comment by TiPunch69** [comment]
Hi!
I tried out the PBEM mode on the old game via Dosbox. 
It works like you described in solution 2. You have to pick in advance that you want to play via mail and then name the save game. Missions are resoved at the end of the game turn and then the game quits (storing the result in the save file). In case of prestige points the oppent gets a misson recap and a prestige first screen.

I looked at the source briefly and there is even the flag for a mail game still in there at some locations.

**Comment by peyre** [comment]
About number 1 above, I've seen many times when a mission failed a die roll and the game said mission control recommends a scrub, but I don't recall ever being given the option to do so - the mission simply continues, for good or ill.  I think it's something that was planned but never implemented.  If that's the case, it potentially removes a complication for PBEM.

I've only played PBEM once myself, though we did play the game to completion (and I got whooped).  I agree with TiPunch - as I recall, the turns looked and felt about normal.  I was the US, and as I recall, I would schedule my missions for next turn, then hit End Turn.  Then I'd decide whether to go ahead with this turn's misssions or scrub them, email the save game to my opponent, then at the start of next turn I would see my missions play out.  Again, that's as I recall - it's been some time.  Incidentally Ryan, if you'd like you and I could start a PBEM game of BARIS CD version so you could get a feel for how it works.

Yes, you have to start the game _as_ PBEM.  BARIS CD version and RIS up to v.1.1 show an option for that (and for Modem) at the main screen, though in RIS those buttons were disabled.

![RISMenu](https://user-images.githubusercontent.com/3118014/81315615-5e709f80-903f-11ea-8ab7-c0f28ae4ef02.jpg)

**Comment by peyre** [comment]
Here we go!  I got the game to start, though it crashes after the first newscast.  But this is the options screen when you select PLAY BY MAIL.

![PBEM](https://user-images.githubusercontent.com/3118014/81504329-67f74300-929d-11ea-86f9-63c3ebbf66a5.png)
