### ISSUE TITLE
Missing file "SENDH.MSG"

### ISSUE THREAD

**Issue by aapo** [raceintospace/raceintospace#139]
Warning:
src/game/fs.cpp:273:try_find_file  can't find file `SENDH.MSG' in game data dir(s)

Referenced in:
./src/game/news.cpp:221:        if ((gork = sOpen((Option == 0) ? "SENDR.MSG" : "SENDH.MSG", "rb", 0)) != NULL) {

(Seems that 'SENDR.MSG' is also missing)

**Comment by peyre** [comment]
Seems this is a part of the messenging system.  I think that in Modem and/or PBEM games, you could click on the Tracking Station to send and receive messages from the other player.  Since both those options are disabled, I'd say this is a moot point - at least until we manage to restore Play by Mail.

**Comment by peyre** [comment]
I don't see this one as a problem.  The one line that refers to them (line 230) adds a message to the newscast saying that the other player has sent you a message, if there is one.  It doesn't hurt anything to leave it in, and would be important to keep if we ever add PBEM back to the game, or even TCP/IP (#131, #174, #346).
