### ISSUE TITLE
Asset licenses?

### ISSUE THREAD

**Issue by kozross** [raceintospace/raceintospace#142]
Are the assets for this game licensed the same way as the code, or differently?

**Comment by tdi** [comment]
+1

**Comment by peyre** [comment]
I wrote to Michael McCarty about this, since the game's ownership reverted to him and Fritz some time ago.  This was his reply; I think we're ok re. licensing.

My feeling is as long as the graphic assets in the project are used within the bounds of this Race Into Space project it's okay to use.

It's not okay to use the music for anything outside of this Race Info Space project.  Doing that would certainly run into trouble with Fritz.  If they want to use any of the music they would have to contact Fritz directly for a license.

Thanks,
Michael

**Comment by rnyoakum** [comment]
If the assets are not approved for use outside of Race Into Space, we should specifically note that any included media (including but not limited to images, video, and audio) are not licensed for any use outside of Race Into Space. This should be included in the Readme file at the least.

**Comment by peyre** [comment]
That's probably a good idea.
