### ISSUE TITLE
Mars, Jupiter, Saturn not showing in Future Missions

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#170]
When Mars, Jupiter, or Saturn is available for a flyby mission, it's supposed to show in Future Missions, but they're not appearing now for some reason.

![saturn flyby](https://user-images.githubusercontent.com/3118014/41500582-4af4c542-7149-11e8-9ff6-4870011910fe.png)

**Comment by peyre** [comment]
Hm, I think I see part of how that screen is drawn.  future.cpp, on lines 127 and 292, calls on fmin.img.0.png, which has Mars, Jupiter, and Saturn in the top left.  Lines 156-178 look like they're meant to take the appropriate parts of the image and superimpose them in the appropriate part of the screen, but somewhere in there it's not getting it right because they never show.

**Comment by rnyoakum** [comment]
I've been rewriting part of future.cpp. It's got a lot of work left to go, but it's hopefully more clear than it was. The issue here was that DrawFuture() handles the initial task of drawing the conditional planets, but isn't used afterwards. Drawing the starfield is handled by Missions() - via ClearDisplay() - which also handles drawing any mission steps. But since Missions() is called at the end of DrawFuture() and every time a new mission is selected, it was drawing over Mars, Saturn, & Jupiter and they were never being redrawn. This is resolved by commit 48fbeb65de76a954d992d684e462383ce8a42d3f.
