### ISSUE TITLE
Show other abilities of candidates?

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#176]
The recruitment screen shows each candidate's skills for Capsule and Endurance, but not the other three (LM, EVA, Docking).  Seems like it might as well show the others too.  Maybe at Astronaut Level 1 it could show them all, at Level 2 it wouldn't show LM or EVA, and at Level 3 it wouldn't show LM, EVA, or Docking (the way it does now at all levels).  Ideally, this should also be something you can turn off in Advanced Preferences so someone can play the game with all three skills masked if they want to.

**Comment by GreenReaper** [comment]
This is obviously deliberate (the first two would be known by the fact that most came in as test pilots, but the others are only known after more specific aptitude tests). 

It might actually make more sense to make it a bit harder - just one of the features known at level one, two or three at level two, and all five at level one.

**Comment by peyre** [comment]
True, the developers figured CA & EN were the only abilities you could reasonably expect to have been evaluated during recruitment.  My thinking has been that it leaves the players often choosing between candidates who are identical except for their name, whereas of course IRL there were all kinds of factors to judge them on that don't have an effect on the game.

I know it would strain realism a bit, but if we loosened that up a little there would be more strategic choices for players to make, rather than eenie-meenie-miney-moeing their way through the list.  I brought it up, though, as an [b]idea[/b], hoping to spark discussion.  It's not at the level of an enhancement request necessarily.

I don't think we should show [i]less[/i] information about candidates, at any rate.  Surely piloting skill was something they could evaluate pretty well, and I know that at least in one case (the one I've read about, the Soviets' first female group), they evaluated and considered the candidates' toughness (EN), so I think both of those skills belong, at least.

**Comment by rnyoakum** [comment]
This sounds like a good idea, coupled with a config option so it can be disabled by players who want the "classic" experience. Any specific proposals?

From a realistic perspective, the player should get at least some information about each candidate because NASA and the Soviets tested each candidate strenuously. I think that should rule out giving no information at Level 3.

From a gamist perspective, giving the player all the information at Level 1 seems reasonable. However, some candidates have strictly better stats than others (Cooper vs Schirra). Because of that, I have reservations about a complete reveal. Alternately, the BARIS manual states:

> Most of the astronauts and cosmonauts of that time period in history are included for game play. Their skills are strictly subjective with an historical flavor for game play. They are not meant to reflect any real life individual's strengths and weaknesses.

which means that the roster stats could be adjusted for a better game balance.

Other things to consider:

- If roster randomization is enabled, my concerns about roster balance are moot. However, the current randomization algorithm will tend to produce far more skilled candidates than the historical roster.
- It's reasonable to have only one change in roster information - say, full information at Level 1 and only Capsule & Endurance for Levels 2 and 3.
- Another approach is to lie in-game about the candidates. Say, provide 3 accurate stats at Level 1, 2 at Level 2, and report 2 stats at Level 3 but any of those stats may be misrepresented by a point either way.

**Comment by peyre** [comment]
I asked Fritz and Michael about the 'naut roster.  They told me they relied heavily on Michael Cassutt's "Who's Who in Space: the First 25 Years" and on conversations with the author, plus some books in Ukrainian.  They used certain outstanding folks (like Ed White & Leonov) to establish what they called a "baseline of the best", and tinkered with the numbers in the roster based on certain people having strong skills in various categories.  For the rest, they basically scattered 0s, 1s, and 2s around randomly.

I'm hesitant to make changes to people's skills (though I wouldn't necessarily be opposed to it if people thought it was a good idea), partly because I'd have to redo my Quick Reference Guide. ;)

I don't think we should make the game give inaccurate information about candidates, since it already does so, effectively.  The figures in the 'naut roster are only what the candidates' skills [i]tend[/i] to be; their actual skills at the end of Basic Training usually come out a bit different (though really high skills tend to be kept).  So there's no need for an additional layer of randomization, to my mind.

My inclination would be to show CA & EN at level 3 (the way it is now), one more at level 2 (maybe DO), and then either one or two more (LM and/or EV) at level 1.  The choice of skills is kind of tricky because in my estimation, DO is the next most important skill after CA--[b]except[/b] if you're flying direct ascent.  Still, I don't have a better idea. 

I do absolutely agree that if we do this, there should be a setting in config to run the game as it was originally, that is to show only CA and EN.

**Comment by GreenReaper** [comment]
Docking makes sense - how many people go direct ascent anyway? I mean, it looks great, but it's not all that realistic.

One thing that occurred to me is that some of the later crops of astronaut might not even have capsule ratings known on the hardest level because they didn't all come in through a route that would test it - however, looking at the timeline, essentially all did in this timeframe apart from a few geologists.
