### ISSUE TITLE
Gemini requires a Jupiter

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#182]
I assigned an Unmanned Joint Orbital Docking test.  When I went to assemble it, instead of a Gemini capsule, it required a Jupiter capsule!!  When I exited the screen and went to look at what was on Pad B (which should have been the capsule), the game crashed, with this message:

raceintospace: /home/leon/raceintospace/src/display/legacy_surface.cpp:295: void display::LegacySurface::copyFrom(display::LegacySurface*, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int): Assertion `srcY1 <= srcY2' failed.
Aborted (core dumped)
![gemini mission requires a jupiter](https://user-images.githubusercontent.com/3118014/42254076-c6d28b8c-7ef9-11e8-8c04-2b6f5853f6d0.png)

**Comment by peyre** [comment]
I just tried this on my laptop to verify that it's not just a problem with my main computer.  Sure enough, if I schedule a Joint docking mission this happens every time.  If I schedule a Single docking mission, selecting the pad in the VAB/VIB makes it crash every time, with the same error message.

**Comment by peyre** [comment]
So, it looks like the game is placing a Jupiter capsule in place of the DM, and maybe not assigning a Primary (capsule) at all, which could be what makes the game crash.

**Comment by peyre** [comment]
So, it looks like the game is placing a Jupiter capsule in place of the DM, and maybe not assigning a Primary (capsule) at all, which could be what makes the game crash.

**Comment by rnyoakum** [comment]
This was actually a combination of two bugs. The Jupiter capsule appearing in place of the DM was due to a bad search/replace in commit 4bc3b361f2f7cf431f4b0cf003b4b64e3ee72cd7, which inadvertently assigned Misc hardware to the Manned array when the project was switching to using enumeration in the code. This is fixed in 856d6973e730a34df12a5833c1d07f48b9f9ea58.

The second problem was in rendering the filler (rocket fuel) for the large casing in the VAB. There was some terse variable naming which seems to have led to the wrong variable being used in a calculation. I've changed some names and added comments to hopefully clarify things for the future (commit 8ecb3525de8ce7a4e590354e3af0f0ad805cb271).
