### ISSUE TITLE
Failure on a Mercury mission shows as an XMS-2, then the Mercury screen crashes

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#183]
I flew a Mercury mission and it suffered a catastrophic failure, but the failure screen showed it as an XMS-2 mission!  Then when I opened the Mercury program and started breaking crews to reassign them, the game crashed.

I had Gemini in development and had also prototyped the Jupiter, since I'd gotten a half-off sale, but didn't have anything to do with XMS-2.
![xms on a mercury mission](https://user-images.githubusercontent.com/3118014/46920481-c0703c80-cfa3-11e8-81e8-5f66525996f6.png)

(I don't know if these are related, but they did happen close together.)

**Comment by rnyoakum** [comment]
I have an issue where attempting to break a crew currently assigned to a planned mission (to launch at turn's end) causes the program to crash, rather than generating a message box. Any chance that you ran into the same error? This is the error output from the crash:

raceintospace: [filepath]/raceintospace/src/display/legacy_surface.cpp:142: void display::LegacySurface::checkPaletteCompatibility(display::LegacySurface*): Assertion `myColor.rgba() == otherColor.rgba()' failed.
Aborted (core dumped)

I also recall seeing the XMS-2 appearing in a failure screen in place of a Mercury capsule, but didn't pay much attention to it at the time, so I can't say when it happened.

**Comment by peyre** [comment]
Yes, I get the same error!  Good catch.  I see that command in line 142; it has a comment saying "if this assertion blows up, you're probably doing a drawing operation without having copied around a palette first" but I don't know what that means or what to do about it.

Say, would you send me an email sometime?  You can reach me at raceintospace at yahoo.com or lordpeyre at yahoo.com.

**Comment by rnyoakum** [comment]
I believe this to be two issues. The first one, the erroneous XMS-2 failure screen, still needs attention. The second issue is that breaking a crew resulted in the game crashing. That should be fixed in commit b13fb2a2d42a7e8bbabb7955ec1dc9ea40b26344. For the record, this is what was happening:

1) The user tells the Capsule building to break a crew. The capsule interface code (in Ast4.cpp) checks the flight code and finds the crew is assigned to a mission.
2) A crew assigned to a mission cannot be broken, which is a reasonable rule. The interface code decides to create a pop-up alert screen saying the crew may not be broken. Interface control will be governed by the alert until it is dismissed.
3) Because the alert will overwrite the Capsule building display, once it is dismissed the area underneath will have to be redrawn. This can be handled by either:
    (A) redrawing all elements it covered, or
    (B) caching the area in a buffer before drawing it, and when the alert is dismissed writing over the pop-up screen from the buffer.
In this case, because the background is static, drawing a small area is less expensive than redrawing everything (a legacy concern, in part), and because it was a lot easier to code, option B was chosen. Which would have been, and probably still is, the right decision.
4) The contents of the rectangle to be covered are copied to vhptr, which is a LegacySurface pointer declared in game_main.cpp, with the intent to copy it back later. This fails.

However, the LegacySurface system represents colors using a color palette, which is why setForegroundColor(3) is passing a number rather than a 32bit color value. As vhptr is a globally accessible variable, another section of code has made use of it so it already has a palette assigned which doesn't match the current display's palette.

I switched from using vhptr to a local LegacySurface buffer. It's not a large buffer, given the restrictions on game height & width, and it matched the solution used elsewhere in Ast4.cpp in the AstLevel function.

**Comment by peyre** [comment]
This one seems to be fixed.  Should we close it?

**Comment by rnyoakum** [comment]
I haven't closed it yet because I'm not sure it's entirely fixed. There were two problems - the failure showing as an XMS-2, and the game crash.The second part was fixed in commit b13fb2a2d42a7e8bbabb7955ec1dc9ea40b26344. The first part, showing an XMS-2 instead of a Mercury capsule, might have been fixed by one of the other broad bug fixes I made, but I never explicitly committed a fix to deal with it. As far as I know, it's still out there; I haven't actually played the game (beyond testing purposes) since November so I haven't had the chance to encounter it. If you've had a Mercury failure that displayed correctly, feel free to close it. We can always reopen if it shows up again.

**Comment by rnyoakum** [comment]
Since the second part, more critical, part of this issue is resolved and several other changes have been made since that may have cleaned up the code, I'm closing this issue. If anyone sees the problem again, I think we should open a new issue that solely references the Mercury/XMS-2 glitch and references this issue. But I haven't heard of it being encountered for a while.
