### ISSUE TITLE
Handling corrupt saves

### ISSUE THREAD

**Issue by rnyoakum** [raceintospace/raceintospace#202]
I'm creating this issue to discuss how the corrupt saves (described in #138) should be handled. My thoughts are:
  I) Label them corrupt and start new games,
  II) Add a config option to allow the loading of corrupt saves, or
  III) Create a utility to try sanitize corrupt saves so they won't load into an unpredictable state

Option I is easy and unhelpful, but might not be a problem. Option II would only cover those saves whose game state information (the Data variable) is good, and would embrace a caveat emptor ideology. It might also cease functioning if the game alters how the Replay/Event information is handled internally, in which case it's a broken hack hanging around. Option III would solve the issue, but would be a lot more work (and thus lower priority).

Any thoughts?

**Comment by peyre** [comment]
As far as I'm concerned, saves we have currently aren't a priority; it's no big deal if we lose current saves.  I'd much rather see the issue fixed, since that'd be a permanent solution.

Incidentally, about the data in saves for regular, modem, and PBEM games: if possible I'd like to keep that stuff around, because I still hold out hope that we can bring back PBEM; it's the one feature BARIS had that RIS doesn't.  (Sure, TCP/IP would be better, but it'd be much more complicated to do than to revive play by email.
