### ISSUE TITLE
Decouple save games from internal data structures

### ISSUE THREAD

**Issue by willglynn** [raceintospace/raceintospace#21]
I'd really like to shuffle around the members of `struct BuzzData`, but I can't because the game assumes old save files conform to that structure layout. We could change the magic number every time we change the save game format, but that's a poor solution. So, let's talk about better solutions.
## Protocol Buffers

[Protocol Buffers](http://code.google.com/p/protobuf/) were created to address this need to sanely version data structures.
- Pro: it lets us be explicit about how data should now be laid out without forgetting about how it used to be structured
- Pro: it cleanly separates the definition of an interchange data structure from the code that accesses it
- Pro: it would be particularly appropriate for use over a network (play-by-mail/Internet multiplayer)
- Con: it's another library
## jsoncpp

Another option would be to use [jsoncpp](http://jsoncpp.sourceforge.net/)'s coercion and default value support:

```
m_name = json_object["name"].asString();
m_female = json_object.get("female", false).asBool();
m_capsule = json_object.get("capsule", 0).asInt();
m_lunar = json_object.get("lunar", 0).asInt();
m_eva = json_object.get("eva", 0).asInt();
m_docking = json_object.get("docking", 0).asInt();
m_endurance = json_object.get("endurance", 0).asInt();
```
- Pro: we already have jsoncpp
- Con: we have to consciously worry about versioning in the code
- Con: ...and we're going to get it wrong somewhere

Even if we pick Protocol Buffers for save games, it shouldn't replace jsoncpp for game data. Game data should be user-editable, and JSON wins there. Moreover, versioning is unimportant since we can to change both the game data and the code that reads it simultaneously. Save games live on-disk, and we're expecting saves to be written by one version and read by another.

Thoughts?

**Comment by hweimer** [comment]
Putting this here because @rnyoakum has mentioned protobufs in #416: I have looked into using protobufs, but switching to them would mean to rewrite basically every single line of the project, as the present layout could no longer be used. Same is true for jsoncpp. As alternatives, I think there are two options: Boost and [cereal](https://uscilab.github.io/cereal/). Boost would be nice because we already depend on it, but different versions are not necessarily compatible with each other, causing trouble for PBEM or when upgrading to a new version. Cereal is just a bunch of header files, so we could even ship old versions within RIS for backwards compatibility. Cereal supports out-of-order loading of XML data, meaning you can change the order of the struct and old games will still load. With Boost that would be at least more complicated. I made some first steps into using Cereal to add serialization to the data structures of the game and besides having to turn most chars into uint8_t it looks promising.

Thoughts?

**Comment by rnyoakum** [comment]
Since I never _connected_ with protobufs, I have no objection to using something else.

For boost, I think the compatibility issue is important; there **are** different versions of boost being used by people who follow the game, so that would be complicated. Per the cereal documentation, different versions of cereal are (likely) not interchangeable. So if it is an issue of requiring a fixed version of either cereal or boost, I would opt for a fixed version of cereal.

Complication: cereal requires the use of C++11, whereas boost serialization - unless I missed something - does not. I've tried to keep everything I do C++ 98 compliant, because it was when I joined the project, and I wanted to maximize accessibility. But I don't know if that matters much anymore, and there are features of C++11 I have longed to use. So I'd want to check and make sure everyone thinks that's the right move to make.

**Comment by hweimer** [comment]
Good point regarding C++11, I wasn't ware of that. On the other hand, for which systems would this be a real problem? Probably RHEL 6, but even that gets EOLed in November.

The problem with compatibility between different cereal versions is not so much that you can't load archives saved with a previous version (if you serialize to a text-based format such as JSON or XML, the last time that happened was in 2014 if I'm not mistaken), but rather that the interface might change. However, even that is probably not a big deal since cereal is header-only, so you can always grab a copy of the version you need without getting into any dependency problems.
