### ISSUE TITLE
Rename the MOL?

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#231]
I've always liked that we have the Manned Orbiting Lab in the game, even though it's really in name only.  What I mean is, the mission in (BA)RIS bears no resemblance to the historical MOL.  It was a single launch mission of a Gemini on top of a booster stage modified to be a temporary spy station.  The mission in (BA)RIS bears a **much** closer resemblance to Soyuz 4/5: two spacecraft dock in orbit and there's maybe a spacewalk between.  

And, of course, the Soviets didn't have an MOL proposal.  They did have Almaz, but that was a full-fledged space station, comparable to Skylab though simpler, at least at first.

So, I wonder if it might be worth considering renaming the MOL mission to something like "Orbital Rendezvous" or "Manned Orbital Rendezvous" if we'd like to keep a resemblance to the original name.

**Comment by rnyoakum** [comment]
I'm fine with renaming it - I'm all for the historical accuracy - but we have to be careful, because the name Experimental Orbiting Lab serves an in-game purpose.

I'll explain using an example. Let's consider Missions 34-36, which are:
34: Joint Manned Orbital Docking EVA Duration
35: Joint Manned Orbitals Docking EVA Duration
36: Joint Manned Orbiting Lab EVA

Missions 34 & 35 are very similar missions, down to the maddeningly similar names. They both provide all the relevant Manned, plus Docking, EVA, & adjustable duration milestones. The difference is that Mission 34 uses a single manned craft (and one unmanned launch) while Mission 35 uses two manned craft, requiring two crews but also spreading the prestige glory among two crews.

Missions 35 & 36 are also mostly alike. They both provide Docking, EVA, & adjustable duration milestones (though the Orbiting Lab has a long minimum duration). The essential distinction is that Mission 36 provides an additional Experimental Orbiting Lab prestige award, and a corresponding milestone penalty until completed.

Unfortunately, this isn't transparent to the player. The manual only distinguishes between Missions 34 & 35 via a single line in the Mission Descriptions table, where Mission 35 has the comment "Requires two spacecraft." This is confusing, since they are both Joint missions, yet the pdf manual lacks even that helpful remark. In-game, there are no such notes; the player only notices the difference if they try out both options and are requested to assign two primary flight crews for Mission 35 instead of the single primary for Mission 34. During mission planning, the similarity between Mission 35 & 36 is worse: they seem to do all the same things, with the same number of steps, and require the same number of crews. Only a single line in the manual, an entry on the Prestige table for Experimental Orbital Lab, alerts the player to the added reward.

Consequently, the phrase "Orbiting Lab" in the mission title is critical because it conveys that there is an additional aspect to "Joint Manned Orbiting Lab EVA" that isn't found in "Joint Manned Orbitals Docking EVA Duration." If we change the name, we need to preserve its usefulness. To me, "Orbital Rendezvous" doesn't work because (I believe) all docking technically involves an orbital rendezvous. Something like "Joint Manned Orbitals Docking (EVA) Joint Duration" might work, but we would need to update the manual to reflect the prestige award. However, that introduces a new source of concern because it would conflict with the pdf manual. So I think we either have to be very careful about changing the name, making sure it is distinctive, informative, and documented, or we need to include a far more comprehensive analysis of the various missions in the provided manual.

**Comment by peyre** [comment]
Oh, dangit!  I forgot about the Manned Orbitals Docking.  Yes, you're quite right, and that's a great catch.   I agree, we can't just go changing the name and leave it at that.  In fact, given our options, I think the best thing to do is to leave things as they are for the time being.  Thanks for spotting that one for me!
