### ISSUE TITLE
Inconsistency in Safety penalty if you don't pay to fix

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#243]
I thought we had an Issue for this, but now I look for it I don't see it.  This seems to be less common than it was--and in fact I thought it had been fixed--but this past weekend I saw it again.  The newscast said I had to pay 10MB or suffer 5% Safety loss, but the prompt to correct it showed a 10% Safety loss instead.

![EVA_newscast](https://user-images.githubusercontent.com/3118014/64223472-04548480-ce89-11e9-9005-a0db0032b2b3.png)
![EVA_Fix](https://user-images.githubusercontent.com/3118014/64223478-074f7500-ce89-11e9-94e1-0fbf04871bee.png)

**Comment by rnyoakum** [comment]
This is interesting, because it is not issue #204 making a reappearance. The particular news event you encountered is event 40, which the code in news_suq.cpp (ln 667) lists as causing -10% damage / 10MB. So I checked the event.dat file, and the text you saw does match what I would expect for event 40 - it starts at byte 4f1a (20250 decimal). But since each event has both US and Soviet text, I scrolled up to the USA event text directly preceding, which reads:

THE SPACE PROGRAM HAS A MECHANICAL ERROR WITH THE 
e PROGRAM. IT WILL COST 10 M.B.'S TO REPAIR OR SUFFER A LOSS
OF 10% SAFETY FACTOR ON THE NEXT MISSION

So, the American text is accurately reflected in the code, while the Soviet telecaster is spreading false information to mask the extent of the troubles faced by Russian engineers. How do you want this fixed? We can
I) Change the text for the Soviet broadcast to match the code, or
II) Change the USA text and the code to match the USSR's version, or even
III) Modify the code to treat the USA and USSR differently.

Your call.

**Comment by peyre** [comment]
Good tracking down there!  I think the simplest and easiest way would be to fix the Soviet text, and I can even do that myself.

**Comment by peyre** [comment]
Ok, I've fixed the Soviet newscast.  Should be ok now, hopefully.
