### ISSUE TITLE
Mission continues after capsule emergency-ejects

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#244]
I just had a mission where the rocket (R-7) exploded on the pad, but the capsule ejected.  The window came up and said the rocket exploded but the capsule ejected safely, but the cosmonaut was injured because the explosion damaged the parachute.  However, the mission then continued as if nothing happened.  There must be something wrong in the mission logic here.  If it matters, this was a manned orbital EVA with a Vostok capsule.

**Comment by peyre** [comment]
This may or may not be related, but I recently encountered this little gem.  Good thing the ejection was successful!

![Good thing the ejection was successful](https://user-images.githubusercontent.com/3118014/89714412-4fa5cb80-d953-11ea-9d03-04299e311a55.png)

**Comment by rnyoakum** [comment]
I've started decoding the different failure cases, so I have some idea about what's going on. These are both launch failures (not minishuttle), which means they are covered by failure mode F000. I'll start with the second case, because it's easier.

I wrote a script so I could examine failure cases in a human-readable format, and  this is the failure condition:

text: 'MAJOR FIRE ON PAD, CAPSULE EJECTION SYSTEM SUCCESSFUL.'
per: 7600
code: 16
val: 50
xtra: 0
fail: 40

The "per" and "fail" fields are used for choosing the failure case and playing any related video, respectively. Text is...yeah. So that leaves "code", "val", and "xtra." Failures get handled by `FailEval(char plr, int type, char *text, int val, int xtra)` in `src/game/mis_m.cpp`. The "code" field is passed into `FailEval` as `type`, val as `val`, xtra as `xtra`. `FailEval` handles code 16 with:

```
case 16:  // VAL% injury,   XTRA% death
    FNote = 0;
    Mev[STEP].StepInfo = 1100 + Mev[STEP].loc;

    for (k = 0; k < MANNED[Mev[STEP].pad]; k++) {
        if (brandom(100) >= val) {
            F_IRCrew(F_INJ, MA[Mev[STEP].pad][k].A);
            Mev[STEP].StepInfo = 2100 + Mev[STEP].loc;
            FNote = 9;
        }        
    }  // for

    ctr = 0; 

    for (k = 0; k < MANNED[Mev[STEP].pad]; k++) {
        if (Data->P[plr].Pool[temp].Status == AST_ST_RETIRED) {
            if (brandom(100) > xtra) {
                F_KillCrew(F_ONE, MA[Mev[STEP].pad][k].A);
                Mev[STEP].StepInfo = 3100 + Mev[STEP].loc;
                FNote = 8;
                ctr++;   
            }        
        }        
    }

    if (ctr == MANNED[Mev[STEP].pad]) {
        Mev[STEP].StepInfo = 4100 + Mev[STEP].loc;
        Mev[STEP].trace = 0x7F;
    } else if (Mev[STEP].fgoto == -1) { 
        Mev[STEP].trace = 0x7F;
    } else { 
        Mev[STEP].trace = STEP + 1;
    }

    if (Mev[STEP].FName[3] == 0x30) {
        Mev[STEP].trace = 0x7f;
    }

    break;   
```

The code starts by rolling a d100 for each astronaut to check for injury but tests if the random value is **greater than** _val_. This doesn't align with the comment "VAL% injury,   XTRA% death." 

```
    for (k = 0; k < MANNED[Mev[STEP].pad]; k++) {
        if (brandom(100) >= val) {
            F_IRCrew(F_INJ, MA[Mev[STEP].pad][k].A);
            Mev[STEP].StepInfo = 2100 + Mev[STEP].loc;
            FNote = 9;
        }        
    }  // for
```

Examining the values assigned to _val_ for failure cases, it should be `if (brandom(100) < val) {`. The check for astronaut death is similar - the comparison uses the wrong operator. It's also wrapped inside a check to see if some other astronaut is retired?!

```
    for (k = 0; k < MANNED[Mev[STEP].pad]; k++) {
        if (Data->P[plr].Pool[temp].Status == AST_ST_RETIRED) {
            if (brandom(100) > xtra) {
                F_KillCrew(F_ONE, MA[Mev[STEP].pad][k].A);
                Mev[STEP].StepInfo = 3100 + Mev[STEP].loc;
                FNote = 8;
                ctr++;   
            }        
        }        
    }
```

Changing those two operators should fix the unsuccessful ejection.

What about that check for the retired astronaut? That check is curious - it doesn't make sense on its own, so my first reaction is to remove it. But it reminds me that there are accidents which result in an astronaut deciding to retire. So I checked the other code 16 failures, and this one stood out

F304
per = 5000, code = 16, val = 50, xtra = 100, fail = 40, text = 'MAJOR FIRE, SHUTTLE IS DESTROYED. '

Of the six "Code 16" failures, four have xtra =0. This one has xtra = 100, which would seem to be 100% chance of fatality. But if so, why the 50% chance of injury? I'm wondering if - for code 16 - `xtra` is supposed to represent _the chance that the injury is fatal_. That's a different interpretation of the comment "VAL% injury,   XTRA% death," but it seems a valid one. Thoughts?

**Comment by peyre** [comment]
That's a tough one.  I can't think why there's that check for a retired 'naut; maybe we should assume it's a mistake and try taking it out?  As for having a val=50 (50% chance of injury) when there's xtra=100 (100% chance of death), perhaps that's an artifact of older coding somewhere along the way.  It might be that whatever-it-was was converted to a flat-out death failure, val was left alone since it's immaterial what the chance of injury is when death is certain to override it.  Just hazarding a guess here.

**Comment by rnyoakum** [comment]
> I just had a mission where the rocket (R-7) exploded on the pad, but the capsule ejected. The window came up and said the rocket exploded but the capsule ejected safely, but the cosmonaut was injured because the explosion damaged the parachute. However, the mission then continued as if nothing happened. There must be something wrong in the mission logic here. If it matters, this was a manned orbital EVA with a Vostok capsule.

This is a code 17 failure case. Code 17 is currently set to either terminate the mission entirely or proceed to the next step. I think it's supposed to branch to the failure state instead. There are three scenarios where a code 17 can occur:

- **Launch**: In this case the mission should branch to the failure case/end.
- **Landing**: Once again, branch to the failure case/end.
- **Mission Activities**: Earth Orbital, Earth/Lunar Mid-Course, and Lunar Orbital activities can experience a loss of atmosphere & cabin pressure. I'm presuming that should branch to step failure rather than proceeding to the next step, unless loss of cabin pressure is recoverable?

**Comment by rnyoakum** [comment]
I fixed this temporarily by emulating the behavior of case 16, which aborts the mission properly. It's a bit of a hack - I think the mission failure branching code needs attention. But until that's done, a temporary solution is better than nothing.

**Comment by peyre** [comment]
I'm sorry, were you looking for input from me back in September (as mentioned in #374)?  I agree that a cobbled-together workaround is better than no fix at all, and a real fix for it would be good but I'm glad for what you've done on it.  Anything more specific you're looking for?  I don't mean to be obtuse but may be missing something.
