### ISSUE TITLE
Adding Duration length in Future Missions?

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#251]
I had a thought the other day: when you schedule a mission with a duration above A, maybe Future Missions should show the duration level, like this.  I know how to do this; I'm just curious whether people think this would be worthwhile.  If not, I'm happy to leave it off.

![Future Missions (C)](https://user-images.githubusercontent.com/3118014/65211559-0b1bf380-da54-11e9-8559-fcbf676f86f5.png)

**Comment by peyre** [comment]
Hum...it sometimes doesn't erase all of what was there before.  The below is from a future.cpp where I added a space to the end, e.g. (C) ".  Somehow adding the space doesn't erase what was there before.  Seems to happen mostly when I'm scrolling _down_ through the missions.  It must be that there's another part of the page that clears the space, and it doesn't go far enough to the right.
![(C)](https://user-images.githubusercontent.com/3118014/65376550-f018d180-dc55-11e9-80e5-08de90465a38.png)

**Comment by rnyoakum** [comment]
Redrawing the mission name, etc. is handled in the Missions function (future.cpp, ln.1465). The specific line that clears the mission name box is `fill_rectangle(6, 31, 182, 46, 3);` on line 1475 as of commit 4c851d242d6ddb9be09ea160e676b60b58936e49. The original code tries very hard to optimize graphics by only redrawing those areas deemed necessary. In this case meant it didn't clear out the entire mission description box; the mission name & duration value never went that far to the right, so they didn't redraw the margin.

From looking at the code where the box is first drawn in DrawFuture(), I'd try replacing it with `fill_rectangle(6, 31, 199, 46, 3);`. I haven't tested it, so that might be a pixel or two too far.

I guess I don't have a problem with adding the (D)uration if you think it'll be convenient, since the duration pie is doing double-duty setting mission length & navigating.

**Comment by peyre** [comment]
Great Ryan!  Thanks.  This was really a low-priority item, but I do think it'd be a nice feature.

**Comment by peyre** [comment]
Dang!  I tried that, and I'm still seeing artifacts.

![A(E))](https://user-images.githubusercontent.com/3118014/65470954-1d19df80-de22-11e9-8ba0-50d487a2aa03.png)

**Comment by rnyoakum** [comment]
If you want to push your working code to a branch on your repository I could take a look at it. If not, I'll try to confirm the correct dimensions for clearing the mission description and let you know.

**Comment by peyre** [comment]
Ok, I tried creating a branch, FMDuration, but I'm not sure it worked.  I'm awfully new at this.

**Comment by peyre** [comment]
The changes I was planning to make were just adding " (A)" " (B)" and so on to lines 1400, 1404, 1408, 1412, 1416, and 1420.  Easy to do yourself if you feel like it.

**Comment by rnyoakum** [comment]
Mea culpa: I pointed you to line 1475, which cleans up the mission description, instead of line 1476, which cleans up the duration. I pushed the correct change, and removed the FMDuration branch.

**Comment by peyre** [comment]
Hey, thanks!  It's a small thing, but I think it makes a nice addition.  Bringing you into it kind of defeated my initial purpose, though: I was hoping to make some kind of contribution to the code that I'm able to do (which is very limited) while you and Petr were busy doing the really important stuff.
