### ISSUE TITLE
Allow longer default name in main screen

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#262]
I would like to change the default name for the Soviet player from Kololov to Korolyov, which would be a better transliteration of his name.  I tried that once several years ago, but for some reason the code limits the default name to 7 characters.  Maybe we should increase the length of the default name by several characters (it will accept 12 characters inputted by the player), and change KOROLOV to KOROLYOV.

**Comment by rnyoakum** [comment]
I think I know what's going on. Which file are you trying to modify, rast.dat or urast.dat?

**Comment by peyre** [comment]
Sorry Ryan, I've been looking for it.  The thing is, this is something I tried to do back when the game was on SourceForge.  I modified the screen to show COSMONAUT SELECTION for the Soviets instead of ASTRONAUT SELECTION, but when I changed KOROLOV to KOROLYOV, it cut off the last character.  I haven't found any notes from that attempt, so I don't recall what file I was editing.

**Comment by rnyoakum** [comment]
My mistake - I'd misread your comment and thought you were encountering this right now. From reading over the code, there shouldn't be any problem changing the default name. I'm not sure why the game limits the player to 12 characters. There are 20 characters allocated for the name, and with the 20th character reserved to null-terminate the name, there should be 19 for use. My guess is that it's a graphical issue, that the game isn't designed to display names beyond 12 characters properly.

You should be able to edit urast.dat easily enough - the Player 2 data is marked by the text PLR2, followed by KOROLOV. You should be able to work in the 12-character space after PLR2 without any problems. I wouldn't try using anything longer, because I assume the RIS programmers added the 12-character limit for a reason. Probably graphics.

Though not knowing about the original problem you encountered years ago, I can take a guess. The urast.dat file is an uncompressed version of the rast.dat file, and it's what the game reads by default. My guess is that the last time you tried to make a change, the urast.dat file didn't exist - the game would have shipped with only rast.dat (being 2.4kb compared with 30+ kb). But, since then, the RIS team decompressed rast.dat and started using urast.dat. Trying to modify the compressed rast.dat file by hand would be... possible, but not worth it.

The game currently reads urast.dat by default, so any changes made should be easily checked. If making any changes, it would probably be best to update the rast.dat file to match, but not essential. I could write a quick script to generate a new rast.dat from the urast.dat if you'd like.

**Comment by peyre** [comment]
The 12-character limit is probably because only 12 characters fit in the box when you type a name.  Sure it could have scrolled to allow you to type more, but 12 is plenty for most people I imagine.

Oh that's neat.  We can handle this however you think best; I'm not particular about the back end.

**Comment by peyre** [comment]
**I fixed it!**  Turns out the names are defined in urast.dat instead of prefs.cpp.  When I modified urast.dat to set player 2 to KOROLYOV, it just worked.
