### ISSUE TITLE
Difference in font size?

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#285]
The CREW STATUS in the mission failure screen bugs me.  To my eyes it looks like the status is shifted down a pixel, but when I zoom in I see it seems instead to be a pixel shorter...yet the characters themselves don't look any different.  The E, for instance, still seems to have one pixel in between each of the bars, or arms, or whatever you call those things coming out from the vertical part.  Anyone have an idea what's going on here?
![Crew Status](https://user-images.githubusercontent.com/3118014/67502781-5751e900-f63b-11e9-9009-53a88434e9af.png)
![Crew Status - Zoom](https://user-images.githubusercontent.com/3118014/67502783-5751e900-f63b-11e9-972e-934e5296b6cb.jpg)

And another closeup, showing E (amost) side by side:
![Screenshot_2019-10-22_20-26-19 Zoom](https://user-images.githubusercontent.com/3118014/67503015-c4fe1500-f63b-11e9-8508-27ee131462e4.jpg)

**Comment by rnyoakum** [comment]
This is the code in mis_c.cpp, function `char FailureMode(char plr, int prelim, char *text)` that prints the "Crew Status" section:
```
draw_string(15, 139, "CREW");

draw_string(9, 146, "STATUS");
```
In the first instance, where Titov is the only cosmonaut, his name is displayed by a call to `GuyDisp(49, 138, MA[Mev[STEP].pad][0].A)` - so, one pixel higher than "CREW." Inside the GuyDisp() function the relevant code is:
```
    draw_string(xa, ya, Guy->Name);
    draw_string(0, 0, ": ");

    switch (Guy->Status) {
    case AST_ST_DEAD:
        display::graphics.setForegroundColor(9);
        draw_string(0, 0, "DEAD");
        break;
```
So the code which displays the cosmonaut name & status uses the same draw_string() function as the "CREW STATUS" text, and the cosmonaut name and status use the same function with the same y-coordinates. I also opened the image in an image editor and drew lines between characters. All the text is the same size.

Conclusion: It's an optical illusion, probably because of the slight offset between "CREW" and the cosmonaut name & the dark red of "DEAD" being darker than the white of "TITOV." There _may_ be an element of how computer monitors physically display pixel colors - the subpixel RGB layout - that contributes to the perception, but I doubt it. Mostly, I think it's that white on black has much better contrast than red on black.

**Comment by peyre** [comment]
An optical illusion!  I had wondered, and that would explain how one part can look one height and the other look a different height, yet looked at differently they both seem to be the same height.  Thanks Ryan.
