### ISSUE TITLE
Launch Pad missing

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#314]
It seems that when you leave the VAB/VIB when there are missions ready to go, the launch pad disappears.  If you then go into any other building and come back to the main screen, it reappears.  Not a big deal, just esthetic, but I thought I'd put it out there.

![Launch pad A missing](https://user-images.githubusercontent.com/3118014/71599569-3ce73080-2b00-11ea-9111-33d3523e41fe.png)
![Launch pad A missing 2](https://user-images.githubusercontent.com/3118014/71599570-3ce73080-2b00-11ea-84c9-34fb0167c645.png)

**Comment by rnyoakum** [comment]
In the case of the second image, that's part of the Port animations - the launch pad isn't there because the rocket/launch assembly is being carried to the launch pad location. Once the animation ends, the launch pad should be present as the rocket is ready for launch. I'm not as sure about the first image, but I think it's the same thing - the port animation shows the rocket being taken into the VAB/VIB for assembly, which would precede the rocket being taken to Pad A.

As you said, it's aesthetic, because you can still mouseover the launch pad space and click on it. Those two animations are triggered by visiting the VAB/VIB; they show the rocket assembly process. When you leave the Port screen to visit building, the current Port animation stops, so Pad A will be displayed when you return to the Port screen.

I believe this is the game working as expected. If you notice the pad missing at any other times, I would consider that an issue. But for this particular situation, I think Pad A should be absent.

**Comment by peyre** [comment]
Oh yeah, that makes sense!  I'll close this one out.
