### ISSUE TITLE
Washout crewman returns to service

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#315]
The newscast said that Kincheloe was a physical washout.  It then sent him to the hospital, which I guess makes sense, except that a few turns later he returned to the Astronaut Complex.  I assume that someone who washes out of the space program should be retired when they get out of the hospital, or am I misunderstanding?

![Kincheloe Washout](https://user-images.githubusercontent.com/3118014/71606052-ad06ae00-2b22-11ea-86a4-3a0cb484ef26.png)
![Kincheloe released](https://user-images.githubusercontent.com/3118014/71606056-b3952580-2b22-11ea-9100-285da6e728c2.png)
![Kincheloe back](https://user-images.githubusercontent.com/3118014/71606059-b6901600-2b22-11ea-8441-c8ce00d6856b.png)

**Comment by rnyoakum** [comment]
There are two "Physical Washout" results that can occur.
1. Physical Washout: Retired
2. Physical Washout: Injured
In the first case, the astronaut/cosmonaut will retire. In the second case, he or she is injured during training and is moved to the hospital. But once he or she is in the hospital, the game doesn't bother what they were doing when they were injured, so it doesn't return them to basic training. Like all injured 'nauts, they're dumped in the astronaut complex.

I think the "Physical Washout" terminology is unfortunate - it does imply the 'naut isn't up to standards, but I don't think that is the game's intention; otherwise, why distinguish between retirement & injury? I doubt any astronaut/cosmonaut who couldn't handle the training would be allowed into space. As I interpret it, the person simply got injured during a difficult basic training regime. If you think it's worth pursuing, it might be possible to change the terminology for injuries. Personally, I would like the 'naut to be returned to basic training after an injury. It shouldn't be too hard to implement, but I don't know if that's the right move.

What are your thoughts?

**Comment by peyre** [comment]
Oh, I see that now!  Yes, it said "injured" right there, yoi.  Yes...I think changing the terminology might be desirable, in principle.  Instead of WAS A PHYSICAL WASHOUT: RETIRED/INJURED, maybe it would be better if it said WAS A PHYSICAL WASHOUT: RETIRED / EXPERIENCED AN INJURY IN TRAINING or something like that.  Of course, that would probably change the hard-coded vs. variable coding, so it may not be very practical.  If not, maybe there's some other change we could make . . . or, we could just leave it alone.  I'm not sure.

**Comment by rnyoakum** [comment]
It's not hard-coded. The news text is found near the end of news.dat. I have the file structure written down in my notes, if you want, or I can modify for you. It should be easy to change.

**Comment by peyre** [comment]
Ahem, so now I see that, yes.  That's what I get for not checking my facts before writing...

So, that gives us a lot of options.  And certainly I can change it if need be.  I'll have to think about it.  Do you have any ideas about what would be best?

**Comment by rnyoakum** [comment]
My preference would be to change the text to something like: "Was injured during training." That would make it clear he/she was only injured and isn't out of the program. Then - and this would take a little more time - I would like it if the astronaut/cosmonaut was returned to training after the injury automatically. Normally you can't return someone to basic training, but since they were struck in the hospital where the player cannot affect the 'naut, I don't think it would be a problem. If the player doesn't want them returned to basic, the player can remove the astronaut/cosmonaut as usual.

**Comment by peyre** [comment]
That sounds reasonable, and more descriptive.  I wish I had saved the game so I could see what Walcrite says in the video.

Returning them to Basic Training is a good idea.  Would they be sent back to Basic I, or to wherever they left off when they were injured?

**Comment by rnyoakum** [comment]
I'd have to check, but I don't think Walcrite has any narration for those events. They just pop up in the news feed, but without any dialogue.

Each astronaut entry tracks their overall training level (basic through advanced), so they would be returned to training at the point they left.

**Comment by peyre** [comment]
Oh yes, that's right--he only reads the first section, and these take place down below.  Perfect then, we can do whatever we like.  Your phrase "was injured during training" is probably best.

**Comment by rnyoakum** [comment]
Per game-logic, setting them back would provide them extra training and thus extra stat boosts, which seems undesirable. In real life, I'm not sure - I don't know enough about the space program to answer that. Was there ever a comparable situation with an astronaut/cosmonaut?

**Comment by peyre** [comment]
Hmm, looking through the list of accidents and injuries in the 60s and 70s on Wikipedia, it looks as though there aren't many precedents: most either didn't injure anyone, killed the guy, or took place after he would have been out of Basic.  We do have two who were injured 9 months in, which would have been Basic II in RIS, and continued with the program.  It looks to me like they picked up where they left off, so I don't see any trouble with us doing the same.

It just occurred to me that "Was injured during basic training" might be even better, and more clear for the user.

**Comment by peyre** [comment]
Ok, here's a handy confirmation of what you thought was going on.  I had two "washouts" in a newscast, one retired and one injured.  The injured one is now in the hospital, and the retired one is gone.  So it works just like you thought it would.  I think I'll change the newscast to say "was injured during training."

![Washout](https://user-images.githubusercontent.com/3118014/73126011-467a8180-3f62-11ea-937e-aed58605ae9c.png)

**Comment by peyre** [comment]
Incidentally, he got out of the hospital after 2 turns, and it put him straight into the Astronaut Complex.  I think he was in Basic III when he went to the hospital though, so he might have been slated to go to the Complex next turn anyway.

**Comment by peyre** [comment]
Ok, finally got confirmation!  In this game, Gordon was injured during training while in Basic II.  Two turns later he's released from the hospital, and he goes to the Astronaut Complex.  So it doesn't send them back to Basic; I think it should, if we can arrange it.

![Released from Hospital](https://user-images.githubusercontent.com/3118014/73236211-62d71380-4146-11ea-9c2b-0c8ff7812644.png)

**Comment by peyre** [comment]
I've updated the file to say WAS INJURED DURING TRAINING rather than WAS A PHYSICAL WASHOUT: INJURED.

**Comment by peyre** [comment]
We can close this one unless you'd like to change it so the 'naut goes back to where he was in Basic Training.

**Comment by rnyoakum** [comment]
I'd actually like to change that, I just haven't gotten around to working on RIS the past several weeks.

**Comment by peyre** [comment]
Not to worry: you're a volunteer, after all.  Thanks for replying to this though; I'll leave it open.
