### ISSUE TITLE
Docking Duration mission doesn't attempt duration

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#322]
This has been an issue since way back in original BARIS, but it didn't occur to me to report it until now.  When you fly a Docking Duration mission, if the docking step fails, it skips the duration attempt.  Unless I'm missing something, a failed docking attempt shouldn't get in the way of the crew continuing the mission and performing duration steps.

![Docking Failed](https://user-images.githubusercontent.com/3118014/73612926-320f3800-45a5-11ea-9c2b-fc56e67112aa.png)
![No Duration attempted](https://user-images.githubusercontent.com/3118014/73612928-36d3ec00-45a5-11ea-9815-511609b6fa9f.png)

**Comment by peyre** [comment]
I just confirmed that also, on a Duration EVA mission, if the EVA fails, it doesn't attempt docking - the same kind of issue as with Duration Docking.

**Comment by peyre** [comment]
I guess when the game tries one of these tests--EVA, docking, possibly also LM test--and that fails, it cancels any other extras and goes straight to deorbiting.  This may be related to #332.

**Comment by hweimer** [comment]
The issue here is that that mission steps can only branch to one other step in case of failure. The default assumption here is that the mission always gets scrubbed entirely on those failures, which makes sense because there are some failures like ""DOCKING ATTEMPTS HAVE FAILED: CRAFT IS WILDLY SPINNING. DOCKING FAILURE", where a continuation of the mission is not what you want to have.
Therefore, one would have to add a second field to Mev to define an alternate branch step in case of minor failures and define an appropriate failure code to handle this. Doable, but since this involves major changes to the data structures, it is probably better to postpone this until proper serialization has been implemented.

**Comment by peyre** [comment]
Yeah, that is tricky.  When RIS was moved here to GitHub, the plan was to convert the hex/binary files to plaintext (in fact it's issue #3).  So if Mev is ever converted to a text file, that might be the time to revisit this one.

**Comment by hweimer** [comment]
There might be an easier way to fix this, however. We could add a new failure code for minor docking failures and check whether the mission involves an LM or an orbiting lab. If no, the mission can continue as planned, as successful docking is not required for the other parts. Otherwise, branch to failure as currently implemented. The only thing I'm not sure about is these weird Jt Lunar Pass/Orbital missions. If they involve docking with a kicker before the TLI, then we must also branch to failure in case of a failed docking.

**Comment by peyre** [comment]
That sounds like a great idea.

True, the oddball missions might take a bit more figuring out.  Sure would be nice, though, to be able to schedule a Docking Duration mission and know it'll attempt duration if the docking test fails - things like that.
