### ISSUE TITLE
Female astronaut

### ISSUE THREAD

**Issue by saka8623** [raceintospace/raceintospace#329]
I want to be able to recruit female astronauts /cosmonauts without resorting to random events

**Comment by peyre** [comment]
I like the ability to recruit women too (I know it's anachronistic - it's my modern sensibilities there).  I like to keep flying them too, even though there's no in-game advantage to it.

This is very interesting.  I've never thought about it before, but maybe we could set it so you always have the _ability_ to recruit women, and the newscast simply makes it mandatory.  And ideally, we could add a line to Advanced Preferences to set it back to the way it used to be, that you can't recruit them unless you get the newscast.  (I like to ensure that people who like the way BARIS used to work can set it back that way if they want to.)

Say saka, you wouldn't be a programmer would you, by any chance?

**Comment by saka8623** [comment]
> I like the ability to recruit women too (I know it's anachronistic - it's my modern sensibilities there). I like to keep flying them too, even though there's no in-game advantage to it.
> 
> This is very interesting. I've never thought about it before, but maybe we could set it so you always have the _ability_ to recruit women, and the newscast simply makes it mandatory. And ideally, we could add a line to Advanced Preferences to set it back to the way it used to be, that you can't recruit them unless you get the newscast. (I like to ensure that people who like the way BARIS used to work can set it back that way if they want to.)
> 
> Say saka, you wouldn't be a programmer would you, by any chance?

No, I have an idea about the game but I'm not a programmer. I need the help of someone with such technical expertise.

**Comment by peyre** [comment]
Ah, you and me both.  I'm able to tinker with the code a bit, but I'm not a programmer either and can't make any kind of substantial changes.  We do have an actual programmer or two active at present, and they may pick this up and make it happen.  Can't say when or even if though; it's strictly a volunteer project and there are lots of bug reports and enhancement requests here already, but we'll have to see.  I've flagged it as an enhancement request of medium priority (that is, I didn't mark it high or low).

**Comment by rnyoakum** [comment]
I think the best way to do this is by adding a new preference option, so the game could be played either way. But which should be the default, the 'classic' approach or universal female astronauts?

**Comment by peyre** [comment]
Well, I'm inclined to have it default to allowing you to recruit them whenever, and let people turn it off if they don't like it that way.

One potential concern about this change is that flying the first woman in space gives a prestige first, so it might lead a lot of players to recruit one or two in Group I, fly one of them, and then never recruit women again.  (Then again, I guess that would sort of mirror history...)

**Comment by saka8623** [comment]
> Well, I'm inclined to have it default to allowing you to recruit them whenever, and let people turn it off if they don't like it that way.
> 
> One potential concern about this change is that flying the first woman in space gives a prestige first, so it might lead a lot of players to recruit one or two in Group I, fly one of them, and then never recruit women again. (Then again, I guess that would sort of mirror history...)

The solution to these problems I thought was to increase the variety of women's prestige on spaceflight and provide a special ending message for the first woman to land on the moon.
However, I don't know if it's appropriate to make such a big change to the original game or if there is a technical means of making such a change in the first place.

**Comment by peyre** [comment]
I think that might be taking it too far.  There's only one endgame, whether you or the computer wins; creating a whole separate one for landing a woman on the Moon seems disproportionate.  I have, however, been working on editing the endgame to show women in a different color, which would highlight the fact - especially if she's the first person on the Moon.

Another thing that's occurred to me that could highlight spacewomen without involving too fundamental a change would be a game mechanic where, if you keep women in your space program (and especially if you keep flying them on missions), you get a little more prestige per turn (or per mission).  The compensating factor would be that the morale of your male astronauts would deteriorate a little faster...it was a sexist time, of course.

**Comment by peyre** [comment]
Ah--**got it!**  In the History screen of the endgame, women now display in a different color.  This one took a while to test; it's hard to get the right conditions to where you can have a woman on the landing.  So here's Wally Funk, the first person to set foot on the Moon!

![Funk is First](https://user-images.githubusercontent.com/3118014/76153829-b2cec180-6086-11ea-9977-bf3030aa8338.png)

**Comment by rnyoakum** [comment]
Hmm... in a separate matter, that picture really effectively shows that there's a palette issue with displaying the person-on-the-moon image.

**Comment by peyre** [comment]
How do you mean?  (If first on the Moon is a guy, he shows in yellow.)

**Comment by rnyoakum** [comment]
The image of the astronaut on the moon (endgame.but.0.png) has a **lot** of blue in it - the same blue used for the text. If you look at the image in a standard image viewer, it doesn't have that blue. There's a palette problem occurring that's causing the image to display incorrectly.

**Comment by peyre** [comment]
Oh yes!  I'd noticed there seemed to be some corruption in the images in the endgame and maybe some other places.  I'm glad you have some idea what's causing it.

**Comment by rnyoakum** [comment]
Okay, I've tested using a configurable option for this, and my solution seems to work. I was about to push when I realized I'd overlooked the AI. How should the AI be impacted by the option?

Normally the AI chooses the astronaut/cosmonauts with the highest Capsule+LM+EVA+Docking total. If required to choose a female candidate by the news event, it will choose all the female recruits first. But if the female_nauts option is selected, should the AI

1. Continue to behave as it always has, only choosing female recruits when the event triggers,
2. Always choose female recruits, as if the news event had always triggered, or
3. Always consider female recruits, but without preference to the men?

**Comment by peyre** [comment]
Good question Ryan!  My instinct is to go with 3.  It seems a shame to take away a possible advantage for the AI, and having it always recruit women doesn't strike me as quite right either.  However, I feel it might be best to defer to how @saka8623 thinks best.

**Comment by saka8623** [comment]
> Good question Ryan! My instinct is to go with 3. It seems a shame to take away a possible advantage for the AI, and having it always recruit women doesn't strike me as quite right either. However, I feel it might be best to defer to how @saka8623 thinks best.

In my personal opinion, I would like you to be able to select option 2 and option 3 if technically possible.

**Comment by peyre** [comment]
We could make that a setting in Advanced Preferences.  It would be a little more involved than just choosing a specific method, but it would fit within our current structure.

**Comment by peyre** [comment]
Another option would be to set it depending on the AI's Astronaut Selection difficulty level:
1 - #2, always choose females
2 - #3, always consider, based on abilities
3 - #1, only choose them if it gets the newscast

**Comment by rnyoakum** [comment]
I pushed a commit (8ea57684b42bd87e2d01caafcf4aeda9cb4c7efa) which should allow this. It creates a new configuration option, female_nauts, which defaults to 0 for the 'classic' experience, or can be set to 1 to always allow female recruits. You can add the option to your config file to start using it immediately. To have the config file include the text comments, you'll have to delete your config file (make a backup!), have the game generate a new one for you, and reset your settings.

In my implementation, I considered whether the flag should force the relevant News Event to occur. That would have reflected the 'historic' aspect of the option. However, since astronauts/cosmonauts are first available in Spring 1958 (turn 3), that would have mandated the news event for one of two turns (Fall 1957 or Spring 1958). I feel it would too strongly dictate the early game news events, so I didn't take that path. Also, well, you're the director of the space agency so you should have some leeway; Race Into Space allows you to recruit Ed Dwight (commit bdca81aabfcad5ffa6883b5be9e938166c1484cb) though the politics of the time interfered.

As for the behavior of the AI, I didn't make that generally configurable. Fundamentally, the game should decide how the AI acts without making that a player choice, and I didn't want to commit our hardworking volunteers to maintaining a wide variety of options. Also, I like Leon's suggestion:

> Another option would be to set it depending on the AI's Astronaut Selection difficulty level

For those "in the know" you can secretly set female_nauts to:

2. Player may recruit female candidates, AI requires the news event.
3. Player may recruit female candidates, AI acts as if the news event was triggered.
4. Player may recruit female candidates, AI is gender-blind when recruiting.

These extra options aren't a commitment and may be changed later. For now, enjoy.

**Comment by rnyoakum** [comment]
Arrgh, I forgot to update the manual with the change.

**Comment by saka8623** [comment]
> Arrgh, I forgot to update the manual with the change.

Please update the manual.

**Comment by peyre** [comment]
Hey, good work.  What happens if female_nauts is set to 1?

I agree with keeping the newscast random.  It was always meant to be a random event, and rather than enable and require you to recruit women, it simply requires you do so.

**Comment by peyre** [comment]
Hey, I see the config file now shows this:

`# Set to determine if female astronauts may be recruited:
#   0  Classic (only after a news event)
#   1  Always allow recruitment
# female_nauts`

wait, wouldn't option 3 be the same as option 1?

**Comment by peyre** [comment]
I just tried this out with config set to 1.  It makes #206 more important than before, since it's helpful to jump down to the bottom and back up.

**Comment by rnyoakum** [comment]
I see the configuration setting as dictating the player's experience primarily. How the AI *operates* is irrelevant, because the player doesn't see anything but the results. So a setting of 1 allows the player to recruit female astronauts/cosmonauts, and how the game chooses to accommodate that - and the possible prestige benefit - should be up to the design team. Currently, ```female_nauts 1``` is equivalent to setting 4, and as implemented always allows AI recruitment, but setting 1 isn't meant to define AI behavior. It's a general "this feature is enabled" kind of setting.

In contrast, I believe listing options 2-4 in the config file feels like a promise that the setup will continue working that way consistently; players shouldn't have to worry that settings will change on them. I'm not sure the game should continue supporting those options, because I think a difficulty-based approach is probably better.

**Comment by peyre** [comment]
Uh oh!  I'm playing a game now; I've received the newscast, so I was required to recruit women and I've been doing it - but now I'm on Group IV and the game won't let me out of the recruitment screen because I haven't chosen any women...but of course there aren't any available in Groups IV or V.

![Won't let you continue](https://user-images.githubusercontent.com/3118014/78457919-a0827c00-7662-11ea-9c55-66d458e34e2a.png)

**Comment by rnyoakum** [comment]
Okay, I know what's going on there, and it's a simple fix. I'll take care of it later this evening when I get the chance.

By the way, it would be nice if we had female candidates in Groups IV and V. Sadly, I'm guessing there just aren't any historical options who were considered during that time period?

**Comment by peyre** [comment]
Great, thanks Ryan!

Yes, that's my understanding, based on my discussions with Fritz and Michael.  Groups I-III used members of the Mercury 13 and the Soviet Female Group.  After then, no women were recruited into either space program until 1978.  The youngest of the Mercury 13 would be kind of a stretch to place in Group IV, and I don't know who we'd use for the USSR.  

For Group V we could, of course, include some of those from 1978 (Sally Ride, Anna Fisher, Shannon Lucid, Judith Resnik, Reha Seddon, Kathryn Sulliavn) and the 1980 Soviet recruitment (Svetlana Savitskaya, Yekaterina Ivanova, Natalya Kuleshova, Irina Pronina, Irina Latysheva, Galina Vasiliyevna, Yelena Ivanovna, Larisa Grigoriyevna, Tamara Sergeyevna).

**Comment by rnyoakum** [comment]
> Uh oh! I'm playing a game now; I've received the newscast, so I was required to recruit women and I've been doing it - but now I'm on Group IV and the game won't let me out of the recruitment screen because I haven't chosen any women...but of course there aren't any available in Groups IV or V. (I have "female_nauts 1" set in my config file btw.)

I've added a fix (0027f87172966b584274f261398540c1c9442fef) for this issue. When I first addressed this I had to separate the idea of female candidates allowed and female candidates required, and didn't think to have the 'required' part dropped for groups IV and V. Very simple change, hopefully you'll be able to continue your game :).

**Comment by peyre** [comment]
Yes!  I redownloaded and compiled, then loaded my autosave, and sure enough it worked.  Thanks Ryan!

**Comment by peyre** [comment]
Well thanks Ryan.  I did, but the computer beat me with a direct ascent approach (how does it pull that off?!).  Anyhow, if you want to add 3 female candidates each to Groups IV and V, I think we can work out reasonably historical names and I've been doing some research toward working out names/identities.  I'd be ok with leaving it alone, but I'm not opposed to including them for IV and V either.  Just let me know whether it's (probably) a good idea to work out a roster or whether it's better to hold off.
