### ISSUE TITLE
Should an emergency abort count as a suborbital?

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#330]
This morning, my first manned launch was a suborbital, as usual, and the rocket exploded - but the launch escape system boosted my astronaut to safety.  Yet at the end of the mission it gave me credit for having flown a suborbital.  Now I know that, technically, that was a suborbital flight of the capsule, but I don't think it's what's really meant by that.

I'm guessing that I've never seen that before because (if I'm not mistaken) it's the first time that my first manned flight has been saved by the launch escape system.

![Emergency features](https://user-images.githubusercontent.com/3118014/76647317-d6c45400-6519-11ea-9d12-64340f4b4c4a.png)

**Comment by hweimer** [comment]
You have seen a code 4 failure on launch, i.e., "NEGATIVE STAGE SEPARATION, CAPSULE EMERGENCY SYSTEMS WORK. RECOVERY REQUIRED." This triggers a branch to a recovery step, although one might politely ask the question why staging was used on a suborbital flight anyway. The only other code 4 failure on launch is for a minishuttle launch:""MAIN ENGINE SHUTS DOWN. MINISHUTTLE MAKES ONE LOW ORBIT AND GOES FOR NORMAL LANDING."

I think in both cases the branch should occur to reentry and not to recovery/landing. That way, it would be clear that a suborbital flight has occurred. If that was what you had planned anyway, well good for you. The game probably should also tie the Manned Space Mission prestige to reentry (currently it's recovery/landing what counts), but if launch branch failures always went to reentry that wouldn't matter.

**Comment by hweimer** [comment]
Actually, that's pretty much exactly what happened with the Atlas-10D launch (aka Big Joe 1), which also crossed the Karman line, although reaching a slightly lower maximum altitude compared to what was planned. Branching to reentry sounds perfectly reasonable here.

**Comment by hweimer** [comment]
I just had a look into how mission.dat would have to be changed and I realized that trying to fix all joint launches would be a nightmare and could well introduce serious bugs if not done properly. I will only have the first launch to branch to re-entry because that's relatively easy to implement (i.e., the second launch will continue to go to recovery/landing upon failure). On the other hand, we should really move the manned space mission prestige to re-entry, otherwise we can have this little gem:

![success](https://user-images.githubusercontent.com/68769393/116620764-905ece00-a942-11eb-941e-07d8e64d5a88.png)

**Comment by peyre** [comment]
Hahaha!  Yes please.  I know a flight on the emergency abort rockets is _technically_ a suborbital flight, but it really shouldn't count.

**Comment by hweimer** [comment]
Okay, then I will leave the launch behavior as it is and fix only the "success" awarding you -7 prestige points.
