### ISSUE TITLE
Lunar Orbital LM Test failure doesn't give credit for lunar orbital

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#332]
I noticed this today.  I flew a Lunar Orbital LM Test and scheduled the landing for next turn.  On the mission, the LM test failed because the crew was unable to dock with the LM.  The MIssion Review screen showed it as a failure with -8 prestige, and when I scheduled the landing for next turn in case the current mission failed, it showed a -3 milestone penalty.  Now sure I should be facing a penalty on the LM steps for not having done an LM test, but the milestone penalty showed I hadn't gotten credit for flying the Lunar Orbital.

**Comment by peyre** [comment]
Ha, it just happened again.  The same thing: Lunar Orbital LM Test, the LM test failed because we couldn't dock with it, and it didn't give credit for the lunar orbital.  I don't know if this is because the test failed because of a docking failure, or if any LM test failure in lunar orbit will cheat you out of credit for it.

**Comment by peyre** [comment]
I wish I understood how the game handles mission failures.  This is my favorite way to do the lunar orbital since it also lets you pick up a couple LM points, but to not get credit for the primary objective (the lunar orbital) because the secondary objective (the LM test) failed...feels like being cheated.  It also makes your choice for how to handle this rather stark.

**Comment by peyre** [comment]
I think this might also be related to #305 and #349.

**Comment by hweimer** [comment]
Just had a manned orbital failing on Orbital Ins Burn with "ENGINE BURN FAILURE, CRAFT OUT OF CONTROL." Mission goes directly to re-entry, but after a successful recovery the Manned Orbital milestone gets awarded. Might be related, if the problem lies in the MisEval handling, but it also could be unrelated if the failure sets the wrong StepInfo.

**Comment by hweimer** [comment]
Just had a manned orbital failing on Orbital Ins Burn with "ENGINE BURN FAILURE, CRAFT OUT OF CONTROL." Mission goes directly to re-entry, but after a successful recovery the Manned Orbital milestone gets awarded. Might be related, if the problem lies in the MisEval handling, but it also could be unrelated if the failure sets the wrong StepInfo.

**Comment by hweimer** [comment]
Just had a manned orbital failing on Orbital Ins Burn with "ENGINE BURN FAILURE, CRAFT OUT OF CONTROL." Mission goes directly to re-entry, but after a successful recovery the Manned Orbital milestone gets awarded. Might be related, if the problem lies in the MisEval handling, but it also could be unrelated if the failure sets the wrong StepInfo.

**Comment by peyre** [comment]
Oops, yep that's another glitch in event handling.

**Comment by hweimer** [comment]
This can probably be traced down the same way as #441.

**Comment by hweimer** [comment]
So, the orbital ins burn thing is because the failure code is 26 (rather than the standard 4 for failure with branch to alternate). 26 is meant to be a worse failure code that permanently lowers the safety of the hardware responsible (though not MaxR&D). However, the code doesn't set PComp like in the failure code 4, so it gets counted as a successful step in the prestige evaluation. Additionally, the comment for code 26 says "Subtract VAL% from Equip perm and branch to alternate", but the actual value being subtracted is brandom(10).
Unfortunately, this also means that the Lunar Orbital bug is unrelated.

**Comment by peyre** [comment]
Good spotting.  I'm glad we're addressing some of these bugs in failure handling.

**Comment by rnyoakum** [comment]
> Additionally, the comment for code 26 says "Subtract VAL% from Equip perm and branch to alternate", but the actual value being subtracted is brandom(10).

I'm guessing this was changed later because of how harsh the penalties are for code 26. 10 of the code 26 errors are in the 8-15% penalty range, but a few of them go up to 65%.

**Comment by hweimer** [comment]
Regarding the original Lunar Orbital issue: @peyre, are you sure that you actually performed a Lunar Orbital? Unless you are on a joint mission, the first docking step is before Lunar Orbital Ins Burn, as it was the case historically. If this docking fails, you should see a branch to failure directly to Trans Earth Injection, meaning you do a Lunar Pass instead of a Lunar Orbital.

**Comment by peyre** [comment]
Well yes.  The crew attempted an LM test, and you can't do that unless you're in lunar orbit.  The mission showed us in lunar orbit, and I thought at the time Well ok, no LM points but at least I've gotten the L Orbital out of the way, but I still showed a milestone penalty before the L Landing.

**Comment by hweimer** [comment]
So, the failure occurred during the second docking step, i.e., after the LM steps, and the LM crew had to spacewalk to the capsule?

**Comment by peyre** [comment]
I forget.  I think we may have failed to dock with the LM or something like that - not sure.

**Comment by hweimer** [comment]
Okay, but the first docking is actually before Lunar Orbital Ins Burn (unless on a Jt LOR mission). For a Manned Lunar Orbital LM Test (mission type 48), the sequence is
D - LUNAR MID-COURSE ACT.
E - DOCKING
F - LUNAR ORBITAL INS BURN
G - LUNAR ORBITAL ACTIVITIES
The Manned Lunar Orbital is awarded on step G. In case step E fails, there is an alternate branch having a different Lunar Orbital Ins Burn, after which you get sent directly via the same Trans Earth Injection step that you will also eventually hit on a successful mission. So, no Lunar Orbital Activities, no Manned Lunar Orbital milestone.

**Comment by peyre** [comment]
Oh wait, I see - so the docking attempt occurs before the orbital.  But even if the LM test can't proceed, shouldn't the capsule go ahead and proceed with the lunar orbital?

**Comment by hweimer** [comment]
>  But even if the LM test can't proceed, shouldn't the capsule go ahead and proceed with the lunar orbital?

That is the same situation as in #322: You can only branch to one other step in case of failure, and the game will always send you home on the quickest path possible.

I think what you really want is to have a downgrade option in case of a failure. One could try to put the steps of the "new" mission to the end of Mev, but if you have multiple downgrades in a row, the struct could fill up pretty quickly.

**Comment by peyre** [comment]
Oh, I see...or rather I get what you're saying in terms of how the game's system works, I think.  As I see it, there are two scenarios with this mission: either you fly it after flying a lunar orbital, so as to gain 2 LM points (like we did with Apollo 10) or you fly it after the lunar pass, attempting to get the lunar orbital and 2 LM points at the same time.

Maybe (if they thought about it), the designers were thinking of the historical scenario: yes, you fly the orbital, then come back later and do the lunar orbital LM test.  I saw the mission and thought Why not do both at once?  But the game doesn't downgrade the mission, as you point out.

I guess it's down to a design/intention thing.  And I'm starting to think the designers might have wanted it to be this way (I can check with them if you think it'd be a good idea).  Possibly what I was trying was _supposed_ to be a gamble, one of the shortcuts you can take a chance on in the game if you're feeling lucky.

**Comment by hweimer** [comment]
I have now implemented a slightly less than perfect solution in #536 that moves the step awarding the lunar orbital from lunar orbital activities to lunar orbital ins burn. I guess this makes sense because the earth orbital is also awarded on orbital ins burn and not on earth orbital activities. I also had to make some other adjustments because the game normally does not award prestige on alternate branches, but here it is reasonable to make an exception.
