### ISSUE TITLE
Warning about LM Penalty?

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#373]
I wonder if it would be a good idea for Future Missions to somehow warn the player that the mission faces a penalty on the LM steps of the mission, if they select a lunar landing and don't have the full 3 LM Points.

**Comment by rnyoakum** [comment]
You're right - the Future Missions penalty display doesn't include the LM penalty, since that doesn't apply to the whole mission. It probably would be a good idea to show it somewhere; personally, I don't check the LM building very often. I don't have a good idea of how to display it, though.

Worth giving a shout-out to issue #168, which would be a good solution to the problem.

**Comment by peyre** [comment]
One possibility that comes to mind, since the LM penalty doesn't show in Future Missions: maybe, if you select a Lunar Landing mission, a Help popup could show explaining that you're shy of 3 LM Points.  However, I could see that being really annoying if you're flipping through missions, since all the lunar landings are all together in the list.

**Comment by rnyoakum** [comment]
A Help popup wouldn't be a good idea while scrolling through missions, as you said, but having a Help message when you press "Continue" would be a different matter - something similar in tone to the message used in the VAB if the player doesn't have a DM in orbit (I155).

**Comment by peyre** [comment]
Oh yeah, something like that would make sense.  I don't know whether it should be one generic "you don't have 3 LM Points" or if we should have three separate ones.

**Comment by peyre** [comment]
This is included in the penalties pop-up we just added to Future Missions.
