### ISSUE TITLE
No Cosmonaut version of Crew Assignment Problem popup

### ISSUE THREAD

**Issue by rnyoakum** [raceintospace/raceintospace#381]
When a player is planning a manned future mission and selects a capsule/orbiter program that does not have sufficient primary (or backup) flight crews available, the Crew Assignment Problem popup is launched. The popup, Help entry i107, refers explicitly to "Astronauts." It would be nice to have a corresponding version referencing "Cosmonauts."

The help entry is only referenced one time in the code, in src/game/crew.cpp, so aside from adding the Help entry this is a one-line change: `Help("i107");` -> `Help(plr == 0 ? "i107" : "iXXX");`

**Comment by peyre** [comment]
That's a pretty good catch.

**Comment by peyre** [comment]
There's another problem here as well.  That Help entry is designed for how BARIS behaved, where you're required to assign a backup crew.  We should probably have one with different wording for when backup crews aren't required. This could expand out to four separate Help entries - maybe it would be better to make it more generic: CREWS instead of ASTRONAUTS, that sort of thing.  Maybe I can work something out with this.

![CrewAssignment](https://user-images.githubusercontent.com/3118014/86539430-222bb500-beb1-11ea-99c6-15aa65e7c4fb.jpg)

**Comment by peyre** [comment]
Ok, I've made the message more generic.  I've also edited crew.cpp to show a different message depending on whether no_backup is turned on.  Now if it's off, it says you have no crews available.  If it's on, it still says you don't have enough crews to assign both a primary and a backup.
