### ISSUE TITLE
Budget dropped like a rock

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#394]
I got the newscast saying an official visited and reports back in Moscow were negative.  I've never known that to have a huge effect on my space program, but this time it seems to have tanked me!  I don't have the funds (in Spring!) to afford even one flight.  Is this because of the newscast?

![Budget 1](https://user-images.githubusercontent.com/3118014/87883303-43b19400-c9bb-11ea-8bc1-94377afa4bde.png)
![Budget 2](https://user-images.githubusercontent.com/3118014/87883304-43b19400-c9bb-11ea-96df-d175da09b071.png)

**Comment by rnyoakum** [comment]
This is interesting. Your news event was

>Event 44
>A POLITBURO MEMBER VISITS THE TRAINING FACILITIES. HE APPEARS TO BE PLEASED, BUT REPORTS FROM MOSCOW ARE CRITICAL OF SPACE OPERATIONS.

But when I check the event code in src/game/news_suq.cpp, the event is handled by:

```
    switch (Data->Events[Data->Count]) {
    case  0:
    case  1:
    case 44:
    case 59:
    case 63:  // Nothing Events
    ...
    case 97:
    case 98:
        break;
```

Since I've never known the wrong text to trigger for an event card, I think this is genuinely a nothing event. So why did your budget drop so precipitously? I don't know. Your prestige is, apparently, neutral so there shouldn't be a prestige hit. There's a semi-random budget adjustment every season, but that can't account for a ~70MB hit. Were there any past budget-related news events?

If you have the game file, I can take a look at it. Otherwise... blame it on a random bit flip caused by a cosmic ray?

**Comment by peyre** [comment]
Oh, sure enough - it wasn't that message that did it.  The previous turn I got a newscast saying the budged will be cut to allow for a military buildup, and it set the budget to 22!

**Comment by rnyoakum** [comment]
Yeah, events 92, 95, and 96 are absolutely brutal... wait...too brutal. **They're bugged!**

Your troubles stem from
> Event 95
> THE MILITARY AND KGB HAVE DECIDED TO CUT FUNDING FOR THE SPACE PROGRAM IN FAVOR OF MORE CONVENTIONAL WEAPONS AND INTERNAL SECURITY. THE SPACE BUDGET HAS BEEN REDUCED TO f M.B.'S.

This event is supposed to reduce your budget by 30% or 30MBs, whichever is less. However, the code for this event in src/game/news_suq.cpp is
```
    case 95:  // 30% or 30MB's whichever is less
        if ((Data->P[plr].Budget / 3) < 30) {
            evflag = Data->P[plr].Budget * 7 / 10;
        } else {
            evflag = 30;
        }

        Data->P[plr].Budget -= evflag;
        evflag = Data->P[plr].Budget;
        break;
```
Instead, it's checking if 1/3 of your budget is less than 30MBs, and if so reducing your budget by 70%! If a third of your budget is greater than 30MBs, you get off with only 30 MBs lost. Events 92 & 96 are similarly devastating.

**Comment by peyre** [comment]
Whoa dude!  Thinking back, I think I might have run into this before, but it's been a while.  Sounds like this might be a really good catch.

**Comment by peyre** [comment]
So, shall I go ahead and fix it, or are you doing something with it?  I don't want to get in your way.

**Comment by rnyoakum** [comment]
Yeah, events 92, 95, and 96 look to be bugged.

I wrote up a fix, but I want to test it first before I commit. I was trying to do too much too quickly yesterday and pushed a commit without testing properly and then had submit a new commit to fix it. So, I want to make sure this fix actually works as it should.

**Comment by peyre** [comment]
D'oh!  Thanks for letting me know.  I'll leave the file alone.  I'm excited you spotted this one though!  Seeing your budget drop so precipitously is alarming.

**Comment by rnyoakum** [comment]
On a related note, the beneficial budget event

> Event 91
> IN THE NEWS TODAY, THE PRESIDENT HAS ANNOUNCED THAT THE SPACE PROGRAM WILL PUT A MAN ON THE MOON WITHIN THREE YEARS. FUNDING HAS INCREASED BY 20 M.B.'S TO SUPPORT THIS EFFORT.

looks like it will never trigger. Early on in the src/game/news_suq.cpp `REvent()` function that handles news events, there's a check
```
    if (Data->Year <= 65 && Data->Events[Data->Count] > 80) {
        return 1;
    }
```
which causes the News to skip any event ID 81+ if it would occur before 1966 (and replace it with a "flavor" event). However, in the code for event 91

```
    case 91:  // increase budget by 20MB's in the budget
        if (Data->Year > 65) {
            return 1;
        }

        Data->P[plr].Budget += 20;
        break;
```
there's a check to skip the event if the year is greater than 1965. In combination, these two checks should effectively prevent event 91 from ever being seen - which is a shame, because it's a true blessing! I'm thinking the check for event 91 is a typo, meant to stop it from triggering before '65. Because it makes more sense to have a three-year goal for a Lunar Landing set after 1965 than before, I was thinking of dropping the check in case 91.

**Comment by peyre** [comment]
That sounds good to me.  Another great catch!
