### ISSUE TITLE
Level 1 is harder at low safety factors

### ISSUE THREAD

**Issue by hweimer** [raceintospace/raceintospace#399]
First of all, thank you for keeping this great game alive!

I've noticed something odd about the random rolls against the safety factors during a mission. On level 1, RIS uses a different random number generator, MisRandom(), which is supposed to be a bit more benign than the brandom() used on level 2 and 3. However, MisRandom() essentially generates Gaussian random numbers with a mean of 57 and a variance of 1000. While this is indeed easier near maximum R&D and above, it is actually harsher than brandom() for safety values of 65 and lower. In practice, this is probably most relevant for the first docking attempts and when using a bad rocket on an unmanned mission.

![rng](https://user-images.githubusercontent.com/68769393/88473093-59264100-cf1a-11ea-9a61-585816b96278.png)

**Comment by peyre** [comment]
Well I'll be!  I had no idea about this.  It seems to me that the game should use a straight random number, not a skewed one.

**Comment by hweimer** [comment]
If my memory serves me right, the skewed RNG was added in one of the first updates to the floppy version because the game was perceived as being too hard. One should also not underestimate the consequences of reverting this change: at 90% safety on a 20-step mission, the odds of getting through without failure is almost twice as large as in the unskewed case.

**Comment by peyre** [comment]
Oh, that's a good point.  I went into that in detail in my guide--so maybe the game is less unforgiving than the numbers would lead you to believe.

Incidentally, would you be interested in working on the game?  You sound like you know your way around this sort of thing.

**Comment by rnyoakum** [comment]
I'm fine with the game slanting things in favor of the player at the easiest difficulty level, though I'm not sure it should be helping out an AI player. One of the historical elements in the code is the EASYMODE bit flag, which is not being used anymore - it is never set when checked, and never checked when set. That, plus the presence of the MisRandom function, suggests there were efforts to help (human) players at the easiest difficulty. Some of these efforts persist, while others may have been removed; the github history doesn't go far enough back to understand the original intent.

A uniform random distribution may be what the game suggests it's using, but isn't what the game *promises* the player. I'd recommend looking at it from the perspective of game design. I see three approaches
1. A uniform random distribution. This is what the game kinda-suggests it's doing, per the % safety rating on craft. It's unbiased and fair - but then again, computer games cheat *all the time* in service of game design.
2. A slightly biased distribution, making it slightly more likely that players on lower difficulties succeed on all mission checks. This approach makes the game a little more forgiving towards novice players. For a game as notoriously difficult as RIS, "slightly easier" may equal "more fun."
3. An RNG such as the one implemented. This approaches uses the RNG to 'teach' the player the 'correct' way to play. The player quickly realizes that their attempts to launch risky missions don't work, and rewards them for using well-researched hardware. Thus, they adapt to the game's preferred approach. On harder difficulties, more experienced players interested in dabbling with riskier strategies have an easier time with that, but find "sure things" aren't as sure.

Of these approaches, I find (1) the most intuitive, (2) probably the best approach, and (3) the most interesting yet also flawed. Often, when games cheat it's to give the players a little nudge - a grace period on button timing, or to prevent that mistake from being immediately fatal.  Approach 1 is exactly what the player expects. Approach 2 is what the player expects, but with a little nudge when things are close. Approach 3 is... an interesting idea, because it dangles itself as good game design but I'm not sure it is; the player _thinks_ they know exactly how the system works, so does the approach actually influence their behavior? The player who launches a mission with hardware rated at 40% knows its a long shot, so making the tests only 30% likely to succeed will just feel like bad luck. The other half of approach 3 - helping out a player when likely to succeed - is just approach 2.

**Comment by peyre** [comment]
I don't have strong feelings about how we handle this one.  I think I'd be ok with any of the scenarios you listed there.

**Comment by hweimer** [comment]
> 3. An RNG such as the one implemented. This approaches uses the RNG to 'teach' the player the 'correct' way to play. 
While I must admit that I didn't think about this third option, applying this here is probably not a good idea for one single reason. Teaching to avoid bad rockets is fine, but the first docking attempts have to be performed at low safety factors, which means this penalty cannot be avoided by proper play.

**Comment by peyre** [comment]
I see you've addressed this in pull request 403.  Good work.

**Comment by rnyoakum** [comment]
> Teaching to avoid bad rockets is fine, but the first docking attempts have to be performed at low safety factors, which means this penalty cannot be avoided by proper play.
> _Originally posted by @hweimer_

Yeah, I'd thought that it was a weak approach, and you're absolutely right about the docking modules. There's just no getting around testing the DM (well, except for Direct Ascent). Level I players start off with only a 30% chance on that first docking attempt, and with the reduced rewards from a failed docking test it makes it much harder to reach that 65% safety break-even point.

One thing I was curious about in your [pull request](https://github.com/raceintospace/raceintospace/pull/403) is an incongruity at `brandom_threshold`. Your function returns `(r_gaussian + 0.5)` to round to the nearest value, but your loop trims the [64.5, 65) range so you're actually less likely to roll 65 compared with 0 through 64, before just pushing above the flat distribution again at 66. It's not a big deal, but I though it an odd blip, so I wondered if you wanted to adjust anything before I approve the commit. No pressure, it's entirely your choice.

**Comment by hweimer** [comment]
>One thing I was curious about in your pull request is an incongruity at brandom_threshold. Your function returns (r_gaussian + 0.5) to round to the nearest value, but your loop trims the [64.5, 65) range so you're actually less likely to roll 65 compared with 0 through 64, before just pushing above the flat distribution again at 66. 

Thanks for spotting this rounding issue. The behavior below brandom_threshold is one thing, but the bigger problem is that random values of 100 are less likely for the same reason. This is certainly wrong, as it makes the rolls easier than what they should be. I have updated the PR so that both ends of the distribution have correct rounding.
