### ISSUE TITLE
Preferences shows sound and music Off instead of On

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#402]
If you load a saved game that had sound and music on, if you open Preferences it will show both buttons set to off, even though sound and music are running.  This is not a big deal; you just have to click on each button twice to turn it off.  Still it's a glitch so I thought I'd report it.

(If you had either sound or music on when you saved the game, the buttons will show correctly.)

![Preferences](https://user-images.githubusercontent.com/3118014/89322871-c08a7200-d639-11ea-885d-b004f4e0e535.png)

**Comment by rnyoakum** [comment]
I'm having trouble reproducing this situation exactly, but here's some related information:

An identical problem to the one described is triggered when starting a PBEM game. When starting a new game - normal and PBEM - the Data settings are initialized from urast.dat. The default values for Sound (`Data->Def.Sound`) and Music (`Data->Def.Music`) are 0 - "off." For a normal game, the Prefs() function sets the Sound and Music values to 1: "on." For PBEM,it does not. However, the sound & music audio channels are not muted to reflect this. The buttons shown in Preferences accurately reflect the Sound and Music values stored in the game data, and toggling them sets the game data _as well as setting the Sound and Music audio channels_. 

Similarly, if I save a game where the Sound and Music settings are toggled "off", exit the program, return, and load the game, the game data will reflect that Sound and Music are set to "off," but the program will play sound and music normally.

Another curiosity is the "audio" option in the config file. According to the description, if set to 0 it disables sound in the game. Instead, it does nothing, and is never referenced outside of options.h/cpp.

**Comment by peyre** [comment]
Tricky!  I'm not sure what to make of that.

Hey, while you're in there, could you get PBEM games to default to Historical Mode?

**Comment by rnyoakum** [comment]
Before this problem is solved, I think the important question is: how should audio be treated? Is audio a game setting, to be tracked within a save file, or is audio a program setting? Personally, I strongly favor the latter - audio is a component of the environment in which the player plays the game, not an aspect of the game instance. Play-by-Email exemplifies this - you could have two players going back and forth, each turn having to reconfigure the sound settings to their preferences.

So I recommend ignoring the `Data->Def.Sound` and `Data->Def.Music` fields entirely. Let audio be stored as a separate configuration file, with configurable music & effects settings (muting, volume). That's going to be a longer task, but a better approach.

**Comment by peyre** [comment]
I would think it would be in the save - if you were playing with the volume off, I'd expect a loaded save to start with volume off.  But, I don't have strong feelings about it.  If you think it should be a game setting, I'm ok with that.  My only concern was that sound was on but Preferences said it was off.
