### ISSUE TITLE
Have half-off sales round up?

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#404]
The discussion of rounding in #399 recalls to mind a question I've been considering: should half-off sales round up instead of down?  As is, they round down, which means that Atlas/R-7 rockets, Cosmos probes, and US docking modules are down from 3MB to 1, effectively 2/3 off.  (Also the Ranger is reduced from 5MB to 2.)

I think if I were creating the game from scratch I'd have wanted to round them up, but at this point in the game, perhaps it's a bit late for that.  Anyone have an opinion on this?

**Comment by rnyoakum** [comment]
As a player, I like costs rounding down :)

As a designer, it's 1MB for each item so it doesn't make large differences. If a player is inclined, they could take advantage to stock up on their supplies of items. But I don't really see that happening, except maybe for US DMs. So I ask, do you find the 1MB influences your purchasing decisions? If so, how?

Personally, a half-off sale is supposed to be that, so I would rather over-discount than under-discount. They're an amazing pair of event cards, and supposed to bring joy and happiness to all they are bestowed upon. So between the two options, I push for the event to be a little better rather than a little worse.

**Comment by peyre** [comment]
Well, if I get it early in the game, I generally stock up on Atlas/R-7s - you can get 18MB worth of them for 6MB.  Still though, since as you point out this mostly affects hardware that's low-cost to begin with, you still end up putting the bulk of your spending into more expensive items.

I have to admit I'm at least partly relieved to hear you suggest keeping it the way it is.  It's a very handy event, and come to think of it, since you see it more often in the fall, rounding up might make it lose a disproportionate amount of its value.  If no one else thinks we should pursue it, I'd be happy to leave it alone.

**Comment by rnyoakum** [comment]
I couldn't remember if there was something pushing it towards the Spring or not; I guess not :(

That's a particularly good reason not to go with increased costs. Getting a half-off event in the Spring is like the winds of opportunity opening a window, tempting you to do something rash and bold. Getting it in the fall is like a chance missed, a promise of glory brought low by earthly concerns. Cheap Atlas/R-7 rockets is a meager consolation prize, at least compared to a Great Big Rocket program.

I'd be tempted to go so far as to have the game _push_ the events towards the spring.

**Comment by peyre** [comment]
Fair enough then, I'm happy to leave this one well enough alone.
