### ISSUE TITLE
Females showing as black in Cemetery

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#406]
In the Cemetery / Kremlin Wall, women show in black, so when not highlighted their names disappear.  The help file says they should show in "light blue", by which I think I meant light purple (color 18) as in several other screens.  This should be simple to fix, but I can't find it anywhere!

![Females show in black](https://user-images.githubusercontent.com/3118014/89592498-98e60600-d801-11ea-8adb-e58326a397a2.png)
![Females show black](https://user-images.githubusercontent.com/3118014/89592339-368d0580-d801-11ea-9abd-4169ff5b05d2.png)

**Comment by rnyoakum** [comment]
As you know, the astronaut/cosmonaut names are displayed using the `DispLeft()` function found in src/game/ast0.cpp. Men are displayed using color 11, women with color 18, and those planning retirement with color 7. Color 7 is pretty dark, but I don't think this is the issue.

I think this is a palette issue caused by the cemetery images. The display uses a 256-color palette system, which isn't ideal, but it was used back in the day to decrease image size on the disk. The hospital/cemetery images load their color palette into the display, which is necessary to display them. The first 32 colors of the palette are set to the same values; well, they're almost always set to the same values. For the cemetery images, only the first 16 colors of the palette are the same as the port's palette. For men, this isn't an issue. For women, color 18 is different with the cemetery palette. For the USSR, it's black.

This is obviously a bad thing, because

1. Rewriting the graphics system to replace the palette system is... desirable, but an epic undertaking,
2. Rewriting the astronaut/cosmonaut display code is also undesirable, because it would probably involve reducing the number of reliable available colors to 16.

But there's a third option

3. Don't overwrite the whole palette when loading the hospital/cemetery images; just load the [32, 256) range.

Unfortunately, if the hospital/cemetery images rely upon the colors in the [16, 32) range that won't look very good, and would require editing the image. With luck, that wouldn't mean altering the image's appearance, rather shifting the palette and the palette indices for the affected pixels. However, I don't think the images use the [16, 32) range. So I *think* the issue can be resolved by not importing the [0, 32) range of the palette.

Since you hopefully have a relevant save (and I do not), could you test this theory? It's a simple change in src/game/ast3.cpp in `InjuredNautCenter()`. Replace `location->exportPalette();` with `location->exportPalette(32, 255);`

Hopefully, that's the solution.

**Comment by peyre** [comment]
Wow, no wonder I couldn't track it down.  Thanks, I'll try that this evening or tomorrow morning.

**Comment by peyre** [comment]
I just tested it, and sure enough that worked!

![KremlinNow](https://user-images.githubusercontent.com/3118014/89699897-3d8a4580-d8df-11ea-9d3b-e068cc15092e.png)

**Comment by rnyoakum** [comment]
Are you pushing the update, or do you want me to handle it?

**Comment by peyre** [comment]
I was going to let you do the honors, but if you're in the middle of other things I'd be glad to commit it.

**Comment by rnyoakum** [comment]
Go ahead - you found the problem and tested it. Seize the glory!

**Comment by peyre** [comment]
Why thanks!  I'll go ahead then.
