### ISSUE TITLE
Not getting Photo Recon for lunar flybys!

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#427]
The last few games I've gotten no photo reconnaissance from doing lunar flybys.  That can't be right.

![LunarPassSuccess](https://user-images.githubusercontent.com/3118014/90989888-ba5d2680-e551-11ea-8d94-86d6414ba6c9.png)
![NoRecon](https://user-images.githubusercontent.com/3118014/90989889-baf5bd00-e551-11ea-90a9-5823fb6ea74c.png)

**Comment by peyre** [comment]
I'm sure this is something else I've done wrong... ;-(

**Comment by rnyoakum** [comment]
Nope, it [wasn't you](https://github.com/raceintospace/raceintospace/commit/b2067d4f1660e9985a6de9443672f02f35913104#diff-e0a3f064d069e734e47a9f17aaa4bbad). The PBEM commit tries to prevent a mail-related double bonus, but the check needs some improvement; it inadvertently disables unmanned photo recon in regular games:

```
    lun = Check_Photo();


    // Don't improve photo recon twice in mail games
    if (!(MAIL == 1 && plr == 0)) {
        lun = 0;
    }
```

Because `MAIL == -1` for a standard game, `lun` will be set to 0 and thus the photo recon bonus is never given.

**Comment by hweimer** [comment]
Yeah, sorry, I botched this up. The negation shouldn't be there, as the case is different from the tests during the manned missions.

BTW: @peyre, did you get me e-mail concerning PBEM playtesting?

**Comment by peyre** [comment]
I didn't!  Do you want to try it?

**Comment by peyre** [comment]
I've just experienced a similar issue.  I had 90% photo recon before launching my lunar landing, but on the mission itself it rolled against a much lower figure.

![Photo Recon bad](https://user-images.githubusercontent.com/3118014/95689008-e34d7f80-0bc2-11eb-8694-c58fabec4005.png)

**Comment by rnyoakum** [comment]
Because you checked Photo Recon and it was at 90%, it seems you were getting credit for your lunar reconnaissance. Since this appears to be a different problem - the Photo Recon check is not rolling against the correct value - I've opened a new issue (#482).
