### ISSUE TITLE
Line drawn in wrong spot in Step Failure

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#474]
In the Step Failure screen, if the craft has more than one crew member, it draws a line between them:
![Line drawn in right place](https://user-images.githubusercontent.com/3118014/94346630-d20d4c00-ffe2-11ea-9f9a-c449a21c8365.png)

But sometimes it draws the line below the two instead:
![Line drawn in wrong place](https://user-images.githubusercontent.com/3118014/94346555-41cf0700-ffe2-11ea-97ce-c923c0b6e485.png)

And just today for the first time, I think, I saw it drawn under the third crew member instead:
![Line drawn in other wrong place](https://user-images.githubusercontent.com/3118014/94346647-eea98400-ffe2-11ea-9754-17b0abc85462.png)

And it occasionally doesn't draw them at all:
![No Line](https://user-images.githubusercontent.com/3118014/94346948-0e41ac00-ffe5-11ea-8314-6101ecfa5e4e.png)

**Comment by rnyoakum** [comment]
Aha! The line is drawn to indicate _which astronaut/cosmonaut is performing the test_:

- The Trans-lunar injection is a **Capsule** test being performed by the Mission Commander Powell
- The Hardware Power-On is a **LM** test being performed by the LM Pilot, Cooper
- The Docking step is a **Docking** test being performed by the Capsule Pilot (aka Docking specialist), Basset
- The Photo Reconnaissance check is not performed by an astronaut or cosmonaut.

So that's the secret of the yellow line. Knowing that, it's kinda useful. Probably should document that somewhere.

**Comment by peyre** [comment]
Oh, wow.  Here I always assumed it was supposed to separate crew members.  Maybe it would be better if we changed the color of the astronaut name or something instead?

**Comment by peyre** [comment]
I wonder if a better idea might be to add: 
[astronaut name]
FAILED ROLL

or something like that, in the gray area beneath "1 VS 91".

**Comment by peyre** [comment]
Got it!  I've gotten it to display the name after "x VS y".  I think I'll close this one, but feel free to reopen if you'd like to change what I've done.
![Failure - Crews](https://user-images.githubusercontent.com/3118014/113488157-23563680-9471-11eb-8c9e-1d41fa1b5e49.png)
