### ISSUE TITLE
Indicate rocket lifting power with boosters?

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#479]
I wonder if it would be helpful if R&D and Purchasing would show the lifting power of each rocket with boosters as well as by itself.  Thoughts?

**Comment by rnyoakum** [comment]
Personally, I think this would not be particularly useful.

My first concern would be how to effectively display the Rocket+Booster lifting value. It would have to be clearly marked so newcomers would understand it. That probably means adding another line, which would make the display very crowded.

_Note: It would be entirely reasonable to rejigger the R&D/Purchasing display so Rockets don't display the "Unit Weight" field, and payload items don't list the "Maximum Payload" field, which would create the space._

My second thought is that I'm not sure how much value it would add. If I'm in R&D or Purchasing and I want to know the lifting power of the rocket+booster combo, it's trivial to navigate between them and do the addition. The problem is that it's usually when I'm looking at _other_ hardware programs - the payloads - that I want to consult the rocket thrust values. The time when thrust/payload calculations would be most relevant - when I'm _planning_ the mission - there's no feedback on the weight or hardware requirements at all.

**Comment by peyre** [comment]
Ah, well this may be another dead-end idea.  The rocketry needed for common missions is shown in the Quick Reference Guide anyway; maybe that's the most appropriate place for it.
