### ISSUE TITLE
Full screen

### ISSUE THREAD

**Issue by donno2048** [raceintospace/raceintospace#481]
I'm using the Windows version and can't find any way to maximize the window

**Comment by peyre** [comment]
Hi Elisha!  Are you running version 1.1 from SourceForge, or did you compile the source here?

**Comment by peyre** [comment]
Ah!  I forget whether that version had the capability to do full-screen; I think it probably didn't.  The current version has an option for it in Advanced Preferences (which wasn't a thing in the SourceForge versions) to do full-screen.  We're hoping to do a release of version 2.0 soon, but it's been slow going.  We've made a whole bunch of improvements since the SourceForge days, but unfortunately there isn't an easy way to install it yet.

**Comment by peyre** [comment]
Incidentally, the recent 2.0 release shows the game window twice as big as it used to.  If you're not able to full-screen it, this should at least be better than it was.

**Comment by donno2048** [comment]
wtf how the hell did you remember this issue

**Comment by peyre** [comment]
I didn't, as such.  I was just going through closed issues, doing a little housecleaning, and I stumbled on this one.
