### ISSUE TITLE
Core Dump

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#501]
I just attempted a lunar landing with Lapot and an LKM.  I got a bad roll and my lander, I think it was, made a fiery crash on the Moon (kbum_01.ogg), and the game crashed before showing the Mission Failure screen.  The first message, of course, is due to space issues (#418), but I assume the second is for the game crash.

`WARNING /home/leon/raceintospace/src/game/vab.cpp:750:DispVA	can't fit LKM image into spaceship casing!
unhandled exception: Error in function HardwareType: argument program is not recognized Misc hardware
Aborted (core dumped)
`

**Comment by peyre** [comment]
Whoa, I encountered the same fiery crash video on lunar approach again just now, and it crashed again.

**Comment by rnyoakum** [comment]
I looked at this, and it's tripping an assertion in the `HardwareType()` function. In part, that's due to a bug in the function - I didn't properly translate text digits to their integer value (an oversight). It's an easy fix.

The weird part is that the function is only called when killing the LM crew, specifically a code 31 flight step error. In that situation, the mission step Equipment should be a capsule, with an ID C? (? representing a digit). But from the error, it would seem to be a piece of Misc hardware.

**Comment by peyre** [comment]
Well...this might be a long shot, but shouldn't it be an LM rather than a capsule?  And the CIA/KGB screens show LMs with Unmanned hardware for space-saving purposes.  I don't think it's related, but thought I'd mention it.

**Comment by rnyoakum** [comment]
I fixed the char-to-int translation issue that was causing the assertion failure in HardwareType() with pull #525. That shouldn't be a problem anymore. I'm concerned there's still something weird going on where sometimes the code to kill the LM crew isn't being passed the right hardware; I added some debugging code to log when it happens. But that's a different problem.

**Comment by peyre** [comment]
Uh oh!  I just saw this one rear its ugly head again!  Same failure, same video, but this time the error message was:

`ERROR   /home/leon/raceintospace/src/game/mis_m.cpp:1429:LMCrew	LMCrew: module ID M5 is not a lunar module
raceintospace: /home/leon/raceintospace/src/game/mis_m.cpp:1433: std::vector<Astros*> LMCrew(int, Equipment*): Assertion `module && HardwareType(*module) == Mission_LM' failed.
Aborted (core dumped)`

**Comment by rnyoakum** [comment]
> Uh oh! I just saw this one rear its ugly head again! Same failure, same video, but this time the error message was:

This is great news! 

> I fixed the char-to-int translation issue that was causing the assertion failure in HardwareType() with pull #525. That shouldn't be a problem anymore. I'm concerned there's still something weird going on where sometimes the code to kill the LM crew isn't being passed the right hardware; I added some debugging code to log when it happens. But that's a different problem. -- rnyoakum

I fixed the bug that was causing the game to abort previously, but as I mentioned the details made me suspect there was another deeper problem I couldn't replicate. Ever since, I've been waiting for you to encounter that problem so the new error logging code could give me a clue and it's finally happened!

**Comment by peyre** [comment]
Oh good, I was hoping my reopening this one wasn't unwelcome.  Normally it sucks to think you've fixed something, only for someone to come back with "Not yet, look at this."
