### ISSUE TITLE
Blank Screen

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#552]
Strange!  I just watched the computer grab a big ol' prestige mission: first Duration C and first flight of a direct ascent spacecraft, but then rather than the game continuing it just showed a blank screen and nothing I press lets me continue.  I ran it from the terminal, but no errors show there.

I couldn't X out either - the game just locked up.  Ending and Stopping didn't work; I had to Kill it to stop the process.

![Blank](https://user-images.githubusercontent.com/3118014/122650103-df74e400-d0e5-11eb-8ac5-29b6b33e8bd5.png)
![CommandLine](https://user-images.githubusercontent.com/3118014/122650104-e00d7a80-d0e5-11eb-9b17-be87fc485eb5.png)

**Comment by peyre** [comment]
Odd!  I loaded the autosave and the game continued fine, though the computer flew the direct ascent capsule without a duration prestige first.  A few turns later it did that Duration C, and crashed like before!  Is there something about watching an LK-700 doing a duration level in the Prestige First screen that makes the game crash?

![DurationC](https://user-images.githubusercontent.com/3118014/122650771-8c049500-d0e9-11eb-8a9c-513e49caff47.png)

**Comment by peyre** [comment]
Haha, I loaded the autosave, saved it out, and proceeded.  The computer flew Dur C again and the game crashed again!  I have the save if anyone wants to try it out themselves.

**Comment by peyre** [comment]
Well I'll be!  I started a new game, since this one looked like it was going to keep crashing.  Flying Gemini again, and the AI selected direct ascent again.  The AI flew a Duration C with its LK-700, and crash again.  At least it's consistent...?

![Dur B   C](https://user-images.githubusercontent.com/3118014/122656979-38f40780-d114-11eb-93ff-b8f8acc854aa.png)

**Comment by peyre** [comment]
I started another game and the AI flew Voskhod & Soyuz as usual, and no crashes.  This must be something specific to direct ascent, or possibly specifically LK-700.

**Comment by hweimer** [comment]
Can you attach the save or send it to me by e-mail? If it's reproducible, I might be able to trace this down.

**Comment by hweimer** [comment]
Okay, I think I know what is happening. The bug is caused by the AI not being able to find a primary crew for a mission and trying to go for an unmanned mission instead. However, the code for this fallback isn't working properly because you cannot simply set the Men variable to zero as unmanned missions actually have different mission codes. In the case of a duration mission, this triggers an infinite loop during because the duration step doesn't exist for unmanned missions, which confuses the game logic. This bug also exists with the other programs, it is just much more likely to show up when flying the four-seater.

I don't what would be the best way to fix this. Is there somewhere a mapping between manned and unmanned missions? Of course, a lunar landing would have to be downgraded to an unmanned lunar orbital and so on. Alternatively, one could try to cancel the mission completely, but that might create other problems.

**Comment by peyre** [comment]
Good finding!  I don't know of a mapping of manned - unmanned missions, no.  It seems to me though that if the AI can downgrade manned missions to unmanned, human players should have the same option.  Or we could simply have the AI scrub missions when there's no crew available.

**Comment by hweimer** [comment]
The actual bug occurs during the planning of future missions, so the AI should certainly be able to downgrade to an unmanned mission if desired.

Turns out that the mapping was not too difficult to implement thanks to the awesome downgrading system. If there is an unmanned counterpart, it can always be found by replacing "MANNED" by "UNMANNED" and go through the list of missions to check whether there is actually a mission named like that. Of course, for some missions like lunar landings that doesn't work, but we can go through the list of downgrading options until we find one that matches. If the only match is "NONE", we fly an unmanned earth orbital as the last resort.

**Comment by peyre** [comment]
Sorry for the delay - I've been on vacation.

Thanks for fixing this!  It was distressing to consider that players could experience crashes from this issue.
