### ISSUE TITLE
Cosmonaut retired when should be injured

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#568]
I flew a Suborbital and the pilot had trouble during the Recovery step (I can't recall what exactly - wish I'd screenshotted it!) that resulted in an injury.  However rather than send the cosmonaut to the Infirmary, it took him off the crew and retired him.

![Cosmonaut Retired](https://user-images.githubusercontent.com/3118014/129449879-f3b8c665-ab08-4c67-89a1-38a4557f09d9.png)
![Removed from crew](https://user-images.githubusercontent.com/3118014/129449888-6bacc7cc-e2a8-4931-88de-e635c56d6e14.png)
![Bykovsky](https://user-images.githubusercontent.com/3118014/129449890-1c88d6d8-a5dd-4fef-b4fc-de1e98490117.png)

**Comment by peyre** [comment]
I have a savegame if that's helpful.

**Comment by peyre** [comment]
Ok, it isn't the one where they're injured because excessive heat causes the cabin to give off excess fumes.  I just got that, and my guy went to the Infirmary as expected.

**Comment by hweimer** [comment]
Both code 17 and 23 failures mean that injuries (which are usually determined randomly) lead to immediate retirement. In some cases, this is even deterministic, as in "PARACHUTE STREAMER, CAPSULE HITS HARD, TOO BADLY DAMAGED TO STAY AFLOAT. CREW BARELY ESCAPES FROM CAPSULE. CREW SEVERELY INJURED AND REMOVED FROM SPACE PROGRAM."

**Comment by peyre** [comment]
Oh, I see!  It does seem misleading to the player; the one I saw didn't indicate my guy was washed out by it.  Maybe the best thing to do would be to edit the failure text to say he retires because of the accident.  If only I had captured a screenshot of it so I knew which to edit.

**Comment by hweimer** [comment]
As in many of these cases, the real issue is that the failure text needs to be sufficiently ambiguous to cover all possible random out comes, often ranging from nothing, to injury and retirement, and death. I think the proper way to address this is to display in the subsequent news that the 'naut was injured and retired. The text "DUE TO A MISSION INJURY" and the proper RetirementReason appear to be already implemented, but it doesn't seem to show up according to your screenshot. It looks like there is only a "Guy->Special = 2" missing in the retirement code, but I will need to test this.

**Comment by peyre** [comment]
Oh yes, I wondered if that were the case.  Thanks!

**Comment by hweimer** [comment]
I also had to add a special check to the news code to list the retirement reason, but now it looks good.

![t](https://user-images.githubusercontent.com/68769393/129491842-b1517a15-3f01-4a9f-af79-d98d420d40d4.png)

**Comment by peyre** [comment]
Wow, that was fast!
