### ISSUE TITLE
Warning about not being able to purchase rockets

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#611]
If you won't be able to purchase rockets or capsules next turn due to a newscast, the Future Missions screen should probably pop up a warning about it - possibly only after you hit Continue, in the case of capsules, since there'd be no need to warn you about probe flybys.

![FutureMissions](https://user-images.githubusercontent.com/3118014/147891109-dc4e6a6a-3f4d-4e24-a266-f53432e8e146.png)

**Comment by peyre** [comment]
Shoot!  I added a Help item and added these lines at line 283 of future.cpp:
    if (Data->P[plr].Rocket[1].Delay > 0) { Help("i169"); }
    if (Data->P[plr].Capsule[0].Delay > 0) { Help("i170"); }

But after I added the second line the compile stopped with Error 2.  Don't know if I need to add an include, or if there's something else wrong here.

**Comment by rnyoakum** [comment]
This doesn't work because `Data->P[plr].Capsule` doesn't exist. You want `Data->P[plr].Manned`  instead.

In theory, you should be checking to see if _all_ Rockets/Capsules are delayed, or just a subset. But practically, that's not an issue at this time if you wish to ignore it. However, you should probably check `Delay > 1` because if `Delay == 1` the player will be able to purchase a rocket/capsule the turn the mission will launch.

**Comment by peyre** [comment]
GOD DAMN!  Ryan you are so cool.

YES that worked.  Thanks!  So the message shows now, but it does in all my saves.  I'll have to experiment with this one.

**Comment by peyre** [comment]
Ah, that was it!  I changed it to this, and now it works - for capsules.  I'll have to playtest

**Comment by peyre** [comment]
Sigh...just played two full games through, never saw the rockets newscast.

**Comment by peyre** [comment]
Ok, finally got the message!  Sure enough it's working for rockets too.  I'll commit this one.

![NoRockets](https://user-images.githubusercontent.com/3118014/148330061-618fbd4d-9ae1-49d9-8380-f73e6d6b903f.png)
![NoRockets2](https://user-images.githubusercontent.com/3118014/148330063-a4de6fb2-de08-4d1a-82fc-0a057401748f.png)
