### ISSUE TITLE
Show damage in the VAB

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#625]
As pleased as I am to have the VAB/VIB showing anything below MaxRD showing in red, and anything damaged shows its safety in deep red, I think it might also be good if it reflected the current safety including the damage.  In this example, the Explorer is at 90% but will be -10% unless I pay to fix it.  I think it would be good if the screen showed 80% for it instead of its regular safety.

![DamagedSatellite](https://user-images.githubusercontent.com/3118014/158034874-f593a31c-df02-4654-b3fa-940b838af14b.png)

**Comment by rnyoakum** [comment]
I think that showing the safety of a damaged component in red is a good idea. Similarly, it's a good idea to reflect any damage in the VAB/VIB, because it reflects the condition of the actual rocket being prepped in the VAB/VIB.

What I disagree with is showing the safety in red if it isn't fully researched. Red commonly means something is wrong, which isn't the case. The Red/Dark Red similarity isn't great, either. I'd rather the VAB highlighted the safety if it is _at or above_ max R&D. With, say, Blue to avoid Red/Green colorblindness problems.

**Comment by peyre** [comment]
Here, I've changed it to yellow for <MaxRD.  How does this look?

![Yellow](https://user-images.githubusercontent.com/3118014/159127131-ad830fd2-911e-46d6-85da-d6411124719f.png)
![More Yellow](https://user-images.githubusercontent.com/3118014/159127146-618b5544-8a5f-45bc-acda-780d1fd7522d.png)

**Comment by rnyoakum** [comment]
I think the yellow is a better scheme than two reds. Personally, I'd prefer a scheme where the numbers are colored if the player is at or above Max R&D rather than below. But a reassuring green would create Red/Green colorblindness issues, so this is the better choice for now.

**Comment by peyre** [comment]
Ok.  The good news of course is that the hard part's done; if we decide on a different color scheme, it's now just a matter of changing the color codes.
