### ISSUE TITLE
Restore the Custom Roster

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#627]
RIS has removed the ability to create or edit a custom roster ("ripped out", as prefs.cpp puts it).  I'm not sure why, though I would guess it's non-free code, but down the road perhaps we should re-add it or rewrite it from scratch.  Screenshots from the floppy version:

![CustomRoster](https://user-images.githubusercontent.com/3118014/159137754-beb3744f-2894-4bdd-990d-a7cf7387e9c2.png)
![CustomRoster2](https://user-images.githubusercontent.com/3118014/166064920-7817e038-625e-4ef0-a148-30f86de09775.png)

I think I would reverse the PLUS and MINUS buttons though.

**Comment by rnyoakum** [comment]
What happens when you click on the Soviet flag? Could you post a screenshot?

**Comment by peyre** [comment]
Oh--sure!  Here you go.

![Roster - Cosmonauts](https://user-images.githubusercontent.com/3118014/166620514-a192b8a4-6c63-4537-a807-53a1df492ebf.png)

**Comment by rnyoakum** [comment]
There are some design differences currently, and it'll be a little rough at first, but...

![RIS-recruit-editor-preview](https://user-images.githubusercontent.com/44246332/166843015-891c1984-b91d-45b0-a98c-69bd2cd5ccf2.png)

**Comment by peyre** [comment]
Wow!  You're actually building it!  :)

**Comment by rnyoakum** [comment]
I added the initial version of the editor. It lacks a few elements but I think it's useful enough in its current form to justify inclusion.

Unfinished aspects include:
- the editor doesn't support modifying an astronaut/cosmonaut's name
- keyboard support is iffy, notably that there are no keystrokes to switch between USA/Soviet rosters or select a skill button
- there is no help file or keyboard support file

I just checked the help.cdr file, and the old help ("I040") and keyboard ("K040") entries are still present.

> Wow, you really built it! And so fast too. This is very neat, just looking over it a little. Two things come to mind.
>
> Per the BARIS manual (p.4), you aren't allowed to exceed the total number of skill points that are in the original roster; you have to take points away from one skill (or one candidate's skill?) in order to give them to another. However, this seems to let you add points arbitrarily; I was able to make all the male astronauts in Group I CA4 without taking any skills from anyone.
>
> Assuming we want to keep the "give some to get some" rule (which is probably a good idea), maybe the screen should indicate somewhere what your current balance is. I don't know where though; I don't see an easy place to put it.
>
> @peyre [comment](https://github.com/raceintospace/raceintospace/pull/642#issuecomment-1119024892)

The notable difference between my implementation and the original game is that it required conservation of attribute points when editing astronaut/cosmonauts. This system doesn't, because
1. it was easier to create a working editor without worrying about that, and
2. because I don't like it.

I recall reading that the original programmers designed the historic rosters to accurately (if crudely) reflect the comparable skills of actual people, based on writings and accounts of the Space Race. Once a player modifies the roster, particularly if they've modified astronaut/cosmonaut names, that conceit is gone. The rosters were only _somewhat_ designed for game balance, and skills are not all equal. So I'm not convinced skill balance is that important, at least for a solo match.

There's also a nagging technical concern. The editor modifies an existing USER.DAT file in the save directory. If none is found, then it uses the original roster as a starting point. If players are allowed to save astronauts/cosmonauts with fewer skill points than originally allocated, that loss of points is persistent. At the moment, trying to restore lost points would require deleting and recreating the custom roster from scratch. **That** aspect could be fixed in a few hours, but is currently low-priority (definitely lower than a skill conservation system 🙂).

That said, a skill conservation system is possible and can be implemented if you have your heart set on it. But I plan to deal with name editing and key commands first.

**Comment by peyre** [comment]
I have my reservations about the current-balance system myself.  I assumed it would be good to keep it to prevent users creating a set of super astronauts...but maybe that isn't necessary.  Maybe it would be good to keep a running tally anyway so users have some idea how far they've deviated from the original total?  Not sure.

Interestingly, there was a cheat in here.  On page 277 of the _Companion_ it says that if you go down to #97 in the astronaut list on the left and change his name to "von Braun", it gives everyone a four in (presumably) all skills.  I had never tried that, so I checked it just now in version 1.01, last of the floppy versions, and it doesn't seem to work, whether I make it one word or two.

Of course, the _Companion_ is written for the CD version, so maybe that was added for v. 1.1.  I can't check that right now; I can do that when I get home.  The CD version is very finicky to get running in DOSBox--at home I have it set up in DBGL, so I can open it there.

**Comment by peyre** [comment]
Ha, no.  I opened the custom roster in the CD version and changed the name to "VON BRAUN" and "VONBRAUN", and neither turned my candidates into super'nauts.  This must be another feature mentioned in the _Companion_ that wasn't actually implemented, like low crew Endurance increasing the milestone penalties of missions.

Incidentally, women showed in red in the custom roster in BARIS.  I don't think we should change what you've done to match it--I think you chose colors we're using elsewhere for females.  I just thought I'd mention it.

![CustomRosterFemales](https://user-images.githubusercontent.com/3118014/167064368-01512504-d46e-42d8-9ec1-d33d3e272f0d.png)

**Comment by peyre** [comment]
Incidentally, in BARIS, clicking on the custom roster button in Preferences first pulled up this confirmation.  I don't know if this is something we want to implement or not, but thought I should bring it up.

![CustomRosterCD](https://user-images.githubusercontent.com/3118014/169099333-ed9d66e6-e169-4f8a-abb4-b711e97a3555.png)

**Comment by rnyoakum** [comment]
I think the custom roster editor is in pretty good shape now, so I'm closing this as an outstanding issue. Feel free to add any more ideas or suggestions to the discussion page, or report any problems as a new issue. As it stands, the task of restoring the Custom Roster seems pretty well handled.
