### ISSUE TITLE
Game refuses to compile now

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#656]
Uh oh.  I downloaded the game this morning and recompiled, and got this.  Did we do a boo-boo?

> /home/leon/raceintospace/src/game/admin.cpp: In function ‘int SaveGame(std::vector<{anonymous}::SFInfo>)’:
/home/leon/raceintospace/src/game/admin.cpp:1942:12: error: ‘struct SaveFileHdr’ has no member named ‘compSize’
 1942 |     header.compSize = interimData.endTurnSaveSize;
      |            ^~~~~~~~
/home/leon/raceintospace/src/game/admin.cpp:1949:39: error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]
 1949 |         write_save_file(filename.c_str(), header);
      |                         ~~~~~~~~~~~~~~^~
      |                                       |
      |                                       const char*
/home/leon/raceintospace/src/game/admin.cpp:1812:28: note:   initializing argument 1 of ‘void write_save_file(char*, SaveFileHdr)’
 1812 | void write_save_file(char *Name, SaveFileHdr header)
      |                      ~~~~~~^~~~
/home/leon/raceintospace/src/game/admin.cpp:1951:38: error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]
 1951 |         write_save_file(savegames[i].Name, header);
/home/leon/raceintospace/src/game/admin.cpp:1812:28: note:   initializing argument 1 of ‘void write_save_file(char*, SaveFileHdr)’
 1812 | void write_save_file(char *Name, SaveFileHdr header)
      |                      ~~~~~~^~~~
/home/leon/raceintospace/src/game/admin.cpp:1954:1: warning: control reaches end of non-void function [-Wreturn-type]
 1954 | }
      | ^
make[2]: *** [src/game/CMakeFiles/raceintospace.dir/build.make:76: src/game/CMakeFiles/raceintospace.dir/admin.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:433: src/game/CMakeFiles/raceintospace.dir/all] Error 2
make: *** [Makefile:166: all] Error 2

![CompileError](https://user-images.githubusercontent.com/3118014/172057258-bb44bd89-4a75-499d-b00c-fa8112e5ac56.png)

**Comment by peyre** [comment]
Oh good, I couldn't figure out what went wrong!

**Comment by peyre** [comment]
Looks like it's still being a problem.

![Compile2](https://user-images.githubusercontent.com/3118014/172247629-a5813978-fa26-4179-a0a4-f2454741e361.png)

**Comment by hweimer** [comment]
The problem lies in the testing code, which treats the Hard variable of a mission as a character string although the game does not use it like this. This is being mentioned in a comment in mission_test.cpp:
https://github.com/raceintospace/raceintospace/blob/19998b906e8b340de3065272fe5de0475b2e4c30/test/game/mission_test.cpp#L16

Previously, this didn't matter, but the newly introduced JSON serialization requires the Hard variable to be an array of 8-bit integers and not a character string. In C++, char and int8_t are not the same thing, so you can't do strcpy on an integer array and the compilation will fail. As a workaround, one can cast Hard to char * and one reproduces the old behavior allowing to compile the tests.

I didn't realize this issue initially because I was building the game with 'make gdb', which for some reason does not compile the testing code. Guess that's another bug.

**Comment by peyre** [comment]
That did it, thanks!
