### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#663]
Uh oh, I just got a core dump!  I don't see a core file (I think they were to be saved in ~/.raceintospace but I don't recall for sure).  My compile command does include TYPE=debug.

`cd ~/ && sudo rm -r raceintospace-build && mkdir raceintospace-build && cd raceintospace-build && cmake -DCMAKE_BUILD_TYPE=Debug ../raceintospace && make && sudo make install && cd src/game && ulimit -c unlimited && ./raceintospace
`

![SegFault](https://user-images.githubusercontent.com/3118014/173247764-1d1d8e9a-74a4-472c-91e8-9e11a6806243.png)

**Comment by peyre** [comment]
Ooh, and I just loaded a random save and got a different one:

![Sanitization](https://user-images.githubusercontent.com/3118014/173248444-71a43293-fde7-4fbf-a87e-16a954bda53a.png)

**Comment by hweimer** [comment]
The first one I don't know, but the second is not a segfault but caused by the recently added sanity checks for save games. Can you upload or send me the save file in question so I can have a look?

**Comment by peyre** [comment]
I'm not sure, but I think this is it.  Anyway I have several save games which segfault, I forget which error. 
If that's solely an issue with saves from previous versions but not current versions, I don't see that we have to do anything about that.  As far as I'm concerned, we don't have to worry about save-game compatibility with earlier versions.  


    On Sunday, June 12, 2022 at 11:51:57 AM PDT, Hendrik W. ***@***.***> wrote:  
 
 


The first one I don't know, but the second is not a segfault but caused by the recently added sanity checks for save games. Can you upload or send me the save file in question so I can have a look?

**Comment by hweimer** [comment]
Thanks for sending the files. I could spot one issue with boostered Saturn V/N1 rockets. Thanks to some index trickery employed by the game, the values stored in the Data structure can actually lie out of values that are sensible if they were used directly for indexing an equipment array. I have fixed this, which addresses the primary issue with these save games.

However, the SOVIETLL game has another issue that is extremely weird. The game stores the number of half-turns it has seen in Data->Count, which is used to access the current news event card number in the Data->Events array. There are at most 42 seasons in a game, which means that Data->Count should not be larger than 84. In your game, it is 98, and I have no idea how that could have happened. The security checks introduced in #655 notice that this is a dangerous value and the game is aborted. You can see the issue when loading the game in an earlier version: After a couple of turns (provided the game does not end before that), you are greeted with the newscast that the space program has a new director, i.e., the very first news event. I vaguely remember having seen this also once in one of my games, but didn't think much about it, as the game _seemed_ to work fine otherwise (it probably didn't because the internal data got corrupted).

**Comment by hweimer** [comment]
Ah, it looks like it has something to do with saving and then loading a game when playing on the Soviet side. The game actually repeats the U.S. turn in that case, which increases Data->Count again when it clearly shouldn't. This is very noticeable in a hotseat game: If you save during the Soviet turn, loading the game will start the turn with the U.S. side again. Is it possible that you were saving and loading a lot during your game?

**Comment by peyre** [comment]
That's possible, I suppose.  Some of my saves are rather old, too.  Can we fix the issue with loaded saves for the Soviet player double-counting US turns?

**Comment by hweimer** [comment]
I guess the best way to fix this is to stop using Data->Count altogether and instead calculate the current half-turn from Data->Year, Data->Season, and the current player. That way it wouldn't matter if the U.S. turn is run twice. The only area where it could make a difference is PBEM games, but I don't remember whether you can save them during the turn at all. Can't check right now because I somehow can't activate PBEM anymore.

**Comment by rnyoakum** [comment]
If I recall correctly, the point of Data->Count is (was?) so that News events are not reapplied when a save is loaded. That was before the save system was updated to store the current status, rather than start-of-turn.

**Comment by pemensik** [comment]
Can you reproduce this bug? Can we fix it before the release?

**Comment by peyre** [comment]
I haven't seen it since I made this report.  Maybe we should close it for now and ignore unless it comes up again?

**Comment by hweimer** [comment]
The issue with Data->Count is reproducible and should definitely be fixed before the release. I will see what I can do in the next days.
