### ISSUE TITLE
Job review gets worse while prestige rises?

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#683]
A user wrote me last night to remark that in the game, his prestige was doing very well, but his job rating was progressively bad.  Anyone know why this might be?  He can be emailed directly at shch0003@yandex.ru if you need details.

![screen1](https://user-images.githubusercontent.com/3118014/191805066-026731de-5f9d-4b0a-a985-540447c4b7b3.jpg)
![screen2](https://user-images.githubusercontent.com/3118014/191805077-677eca15-23f6-45f6-8077-6ecdd385fbec.jpg)

**Comment by hweimer** [comment]
I think this is an issue related to #676. Whether a turn is treated as new depends on the value stored in Data->P[0].eCount, but if the U.S. player is an AI, this will never get updated because AI players use a different function for news events. Which means that the job review gets updated a second time everytime you load a game, which makes things worse if your performance is negative.
