### ISSUE TITLE
Problem in hardware.cpp

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#702]
This morning I downloaded the game to make sure I had the latest, then overwrote with some experimental files I have (ast0.cpp, event.dat, mis_m.cpp, news.cpp, news_suq.cpp) and compiled.  I haven't changed hardware.cpp.  It compiles and runs, but at the end of my first time, as either the US or USSR, the game shows the "Computer Thinking" screen, but without the country's insignia, then crashes with the following error:

```
raceintospace: /home/leon/raceintospace/src/game/hardware.cpp:132: Equipment& HardwareProgram(int, int, int): Assertion `player >= 0 && player < NUM_PLAYERS' failed.
Aborted (core dumped)
```

![NoInsignia](https://user-images.githubusercontent.com/3118014/195999790-83bc4ddf-6150-4a27-a640-25f24c490073.png)

**Comment by rnyoakum** [comment]
The problem is that the global variable `plr[1]` (and probably `plr[0]`) is getting set to a value other than 0 or 1. That much is clear from the Next Turn screen; an impermissible value is being passed so it defaults to the USSR text and can't load the value.

In game_main.cpp you'll find this snippet handling when the turn advances:

```
            if (!AI[i]) {
                NextTurn(plr[i]);
                VerifySF(plr[i]);
```

The wrong value is sent to NextTurn(), which tries to display the Next Turn screen. The function can't do it's job since it's being given an invalid country selection, but makes the attempt. Then it tries to verify the Hardware Safety factors, but in VerifySF an invalid country selection (as in, not 0 or 1) would result in an out-of-index error so an assertion catches the mistake and kills the program.

Are you having this problem with the current build or only when you add your experimental code?

**Comment by peyre** [comment]
That's a very good question.  To do a fair test, I downloaded the code and compiled without making any modifications.  It did the same thing.

**Comment by hweimer** [comment]
This is a regression introduced by #699. While the problem is related to the plr[] array, the problem is actually caused by plr[i] being 0 or 1 for an AI player. The game expects plr[i] to be 2 or 3 in that case, and the game crashes if that's not the case.
