### ISSUE TITLE
Game Freezes

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#726]
I was just flying a Lunar Orbital LM Test with a Kicker-C (you can do that by scheduling a Soyuz LL and then downgrading it).  I rolled a fail: as I recall, Thruster fails to shut off. Probe crashes on the surface.  Then it went to the next screen, and locked up.  No messages in the terminal window.  I had to kill the process to quit the game.

![Game Freeze](https://user-images.githubusercontent.com/3118014/208313540-f787783c-d581-4562-99d0-2d90abf64ed7.png)

**Comment by hweimer** [comment]
I can reproduce this, which even happens when the mission is sort of completed successfully. (In fact, it isn't because you go straight from LEM ACTIVITIES to TRANS-EARTH-INJECTION, which creates havoc during prestige evaluation.) The real issue is that it doesn't make sense to fly an L.M. test with a KICKER-C, so you shouldn't be able to downgrade to that. I will address this together with #713.
