### ISSUE TITLE
Paying to fix damaged capsule didn't fix it

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#737]
My Mercury needed 10MB or I would face a 10% penalty on the next mission.  I paid to fix it, but if I'm not mistaken from the chart here, the penalty applied anyway.  My Mercury was at Max R&D, 78%.

![Damaged equipment](https://user-images.githubusercontent.com/3118014/213878417-99475067-b4ed-46c0-9ece-dfa27bccd3e1.png)

**Comment by rnyoakum** [comment]
It does look like there was a problem. Do you have a save from before the mission you could send me?

**Comment by peyre** [comment]
I thought you might ask!  Save emailed to you.

**Comment by rnyoakum** [comment]
Okay, this was a fun one. Each piece of equipment has a variable SMods that tracks the safety modifiers for that particular piece of equipment. All of the safety modifiers for a piece of equipment are added up into SMods and this value is then added to the mission score for the piece of equipment (MisSaf):

>  *src/data/mc2.cpp:841-2*
>```
> eq->SMods += eq->Damage;    //Damaged Equipment, Nikakd, 10/8/10
> eq->MisSaf = eq->Safety + eq->SMods;
>```

I don't know why SMods, MisSaf, etc. are stored in the player data rather than being temporary values established per mission. Perhaps there were unimplemented plans to add one-time bonuses to equipment performance or it was old-school memory management tricks. But the point is that **they persist between missions**.

In practice, SMods is only ever used to store the equipment damage modifier. In a game, it works like this:
- At the start of the game, (equipment)->SMods is set to 0.
- At the start of a mission using the equipment, SMods is **incremented** by the (equipment)->Damage.
- At the end of a mission **where the equipment was used** (equipment)->SMods is reset to 0, along with (equipment)->MisSaf and (equipment)->Damage.

and that's the lifecycle of the SMods variable. I've emphasized the key parts.  So here's what happened:

1. In the Fall of 1959, your Mercury program was damaged. You had to pay 10MB or suffer a -10% Safety Factor to your next mission. At this point, you don't pay.  *(Mercury)->SMods = 0*
2. Come Spring 1960, you have a Suborbital mission planned and you launch it. The capsule is still damaged. *(Mercury)->SMods = -10*
3. The mission fails, but it fails on the launch stage. The Mercury capsule isn't used, so the Mercury capsule is still damaged. Critically, this means the SMods value is not reset. *(Mercury)->SMods = -10*
4. You, not wanting to risk another catastrophe, pony up the cash to fix the Mercury program. *(Mercury)->Damage* is reset to 0. *(Mercury)->SMods = -10*
5. You launch the Mercury II capsule. There's no damage, so SMods isn't incremented. But it's still set to -10, so *(Mercury)->MisSaf = (Mercury)->Safety + (-10)*.

This is a pretty rare problem, so consider it a harsh lesson for not repairing your equipment. However, it is an easy issue to fix. Since SMods only get used in one place - _and as temporary storage_ - the easy solution is to change

>  *src/data/mc2.cpp:841*
>```
> eq->SMods += eq->Damage;    //Damaged Equipment, Nikakd, 10/8/10

to

>  *src/data/mc2.cpp:841*
>```
> eq->SMods = eq->Damage;    //Damaged Equipment, Nikakd, 10/8/10

It's that simple.

**Comment by peyre** [comment]
Wow!  Your ability to track these down never ceases to amaze me.  So, should I make the change or were you thinking of doing it yourself?

**Comment by peyre** [comment]
Sorry, I missed your question at the end!  D'oh...  Anyway, I ran into this issue again today:
![Hardware not fixed](https://user-images.githubusercontent.com/3118014/218273444-c2b762a0-89fd-429b-b6f9-77df98fe6199.png)

So I closed out of the program, made the change, and ran the mission from Autosave.  Much better now!  I'll commit the change.  Thanks so much.
![Damage Fixed](https://user-images.githubusercontent.com/3118014/218273478-41d289e5-b7df-42c0-84e3-d8b84b76edea.png)

**Comment by rnyoakum** [comment]
I made a slight change - when reviewing the solution I had suggested I realized I didn't like it, because it blanked any value stored in Smods. Practically, that made no difference, but it meant Smods was useless for any future changes. So I pushed 4c7f5daca68962ace8c554091f799babfb6ec1f2 to delink Smods and Damage instead.

```
// SMods no longer adjusted by eq->Damage.
eq->MisSaf = eq->Safety + eq->SMods + eq->Damage;
```

**Comment by peyre** [comment]
Sounds good!  Thanks for checking on it.
