### ISSUE TITLE
Core Dump

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#755]
The game just crashed in the middle of an EVA Duration mission, around the time of the spacewalk.  The terminal shows the following:

```
WARNING /home/leon/raceintospace/src/game/fs.cpp:279:try_find_file	can't find file `SATN_13.ogg' in audio dir(s)
WARNING /home/leon/raceintospace/src/game/fs.cpp:279:try_find_file	can't find file `NONE.ogg' in audio dir(s)
WARNING /home/leon/raceintospace/src/game/fs.cpp:279:try_find_file	can't find file `NONE.ogg' in audio dir(s)
WARNING /home/leon/raceintospace/src/game/fs.cpp:279:try_find_file	can't find file `NONE.ogg' in audio dir(s)
unhandled exception: vector::_M_range_check: __n (which is 2954) >= this->size() (which is 2954)
Aborted (core dumped)
```

**Comment by hweimer** [comment]
I have rewritten the sequence selection code, which should take care of these crashes. However, the underlying issue is likely some missing or incorrect entries in (f)seq.json, of which there are probably plenty around. (This is independent of the recent move to a JSON format, it's just that this made these errors very noticable by crashing the game.)

**Comment by peyre** [comment]
That may be a good thing!  It'll let us fix bugs that have been hidden in the past.
