### ISSUE TITLE
Round off rather than down?

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#833]
I could definitely be mistaken, but when the game rounds, I think it rounds _down_, so like 2.8 would be rounded down to 2.  Assuming that's right, I wonder if we could have it round _off_ instead, so 2.2 would become 2, but 2.8 would be rounded to 3.  I'm thinking especially of things like crew endurance contribution to Duration steps of missions, and maybe rocket+booster combo (except if the user has rocket+booster Safety set to the average of the two, as in Classic settings).

**Comment by rnyoakum** [comment]
It already tries to round to the nearest integer for average crew endurance.  In src/game/mc2.cpp

```
int CrewEndurance(const struct MisAst *crew, size_t crewSize)
{
    assert(crew);

    int value = 0;

    for (size_t i = 0; i < crewSize; i++) {
        assert(crew[i].A);
        value += crew[i].A->Endurance;
    }

    return int((double(value) / double(crewSize)) + 0.5);
}
```

It converts the total endurance and crew size to doubles before dividing and adds 0.5 so everything will be rounded when the conversion back to an integer lops off everything after the period.

I should modify it to remove the integer->double->integer conversions  but since crew size is in the range of 1-4 in practice there shouldn't be a problem.

**Comment by peyre** [comment]
Oh, excellent!  I was assuming wrong then.  Maybe I should just close this one.
