### ISSUE TITLE
Sanitization check failed

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#834]
The game crashed on me today.  I think I had just scheduled a Duration Docking mission.  This showed in the terminal:

`unhandled exception: Sanitization check failed: Assign >= 0 && Assign <= NUM_PROGRAMS + 1 (/home/leon/raceintospace/src/game/data.h:550)
Aborted (core dumped)
`

I don't _think_ this is related to my having added the Race characteristic to crew.json, but it's the only change I've made recently.

**Comment by hweimer** [comment]
This looks like a wild pointer having corrupted the data struct. Do you have an autosave file?

**Comment by peyre** [comment]
I've emailed it to you.

**Comment by hweimer** [comment]
This is similar than the bugs we saw when introducing a global index for the human player naut selection that caused havoc when it ran past 128. This time, it occurred in the AI code, where I thought I had double-checked all variables being of the appropriate type. Turns out there was one global variable I had missed.
